changelog:
  categories:
    - title: Features
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Security
      labels: [security]
    - title: Maintenance and other changes
      labels: ['*']
