#!/usr/bin/env python3
"""Mirror canonical agent skills into platform-specific directories."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from "
GENERATED_SUFFIX = ". DO NOT EDIT. -->"
MAX_SKILL_RESOURCE_FILES = 512
MAX_SKILL_RESOURCE_BYTES = 2 * 1024 * 1024
MAX_SKILL_TOTAL_BYTES = 16 * 1024 * 1024


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def generated_content(source_rel: str, source_text: str) -> str:
    return f"{GENERATED_PREFIX}{source_rel}{GENERATED_SUFFIX}\n\n{source_text}"


def canonical_skills(root: Path) -> dict[str, Path]:
    src_root = root / ".ai" / "skills-src"
    skills: dict[str, Path] = {}
    if not src_root.exists():
        return skills
    reject_symlink_components(root, src_root, "read canonical skill resources")
    for skill_root in sorted(src_root.iterdir()):
        if skill_root.is_symlink():
            raise ValueError(
                f"refuses to read a symbolic link in canonical skill resources: {skill_root.relative_to(root)}"
            )
        if not skill_root.is_dir() or not (skill_root / "SKILL.md").is_file():
            continue
        skills[skill_root.name] = skill_root
    return skills


def skill_files(skill_root: Path) -> list[Path]:
    if skill_root.is_symlink():
        raise ValueError(f"refuses to read a symbolic link in canonical skill resources: {skill_root}")
    resolved_root = skill_root.resolve(strict=True)
    files: list[Path] = []
    total_bytes = 0
    for source in sorted(skill_root.rglob("*")):
        if source.is_symlink():
            raise ValueError(
                f"refuses to read a symbolic link in canonical skill resources: {source.relative_to(skill_root)}"
            )
        if source.is_dir():
            continue
        if not source.is_file():
            raise ValueError(f"refuses unsupported canonical skill resource type: {source.relative_to(skill_root)}")
        try:
            source.resolve(strict=True).relative_to(resolved_root)
        except ValueError as exc:
            raise ValueError(
                f"refuses canonical skill resource outside its skill root: {source.relative_to(skill_root)}"
            ) from exc
        size = source.lstat().st_size
        if size > MAX_SKILL_RESOURCE_BYTES:
            raise ValueError(
                f"canonical skill resource exceeds {MAX_SKILL_RESOURCE_BYTES} byte limit: "
                f"{source.relative_to(skill_root)}"
            )
        files.append(source)
        total_bytes += size
        if len(files) > MAX_SKILL_RESOURCE_FILES:
            raise ValueError(f"canonical skill exceeds {MAX_SKILL_RESOURCE_FILES} resource limit: {skill_root.name}")
        if total_bytes > MAX_SKILL_TOTAL_BYTES:
            raise ValueError(f"canonical skill exceeds {MAX_SKILL_TOTAL_BYTES} total byte limit: {skill_root.name}")
    return files


def reject_symlink_components(root: Path, candidate: Path, operation: str) -> None:
    try:
        relative = candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"refuses to {operation} outside the repository: {candidate}") from exc
    current = root
    if current.is_symlink():
        raise ValueError(f"refuses to {operation} through a symbolic link: {current}")
    for part in relative.parts:
        current /= part
        if current.is_symlink():
            raise ValueError(f"refuses to {operation} through a symbolic link: {relative}")


def is_generated(text: str) -> bool:
    return text.startswith(GENERATED_PREFIX)


def sync(check: bool = False) -> int:
    root = repo_root()
    failures: list[str] = []
    try:
        skills = canonical_skills(root)
        sources = {name: skill_files(source_root) for name, source_root in skills.items()}
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    destinations = [
        root / ".agents" / "skills",
        root / ".claude" / "skills",
        root / ".cursor" / "skills",
        root / ".windsurf" / "skills",
        root / ".cline" / "skills",
        root / ".github" / "skills",
    ]
    for dest_root in destinations:
        try:
            reject_symlink_components(root, dest_root, "write generated skill resources")
        except ValueError as exc:
            failures.append(str(exc))
            continue
        dest_root.mkdir(parents=True, exist_ok=True)
        expected_destinations: set[Path] = set()

        for name, source_root in skills.items():
            for source in sources[name]:
                source_rel = source.relative_to(root).as_posix()
                expected = generated_content(source_rel, source.read_text(encoding="utf-8"))
                dest = dest_root / name / source.relative_to(source_root)
                expected_destinations.add(dest)
                try:
                    reject_symlink_components(root, dest, "write generated skill resources")
                except ValueError as exc:
                    failures.append(str(exc))
                    continue

                if check:
                    if not dest.exists():
                        failures.append(f"missing generated skill resource: {dest.relative_to(root)}")
                        continue
                    actual = dest.read_text(encoding="utf-8")
                    if actual != expected:
                        failures.append(f"generated skill resource drift: {dest.relative_to(root)}")
                else:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    dest.write_text(expected, encoding="utf-8", newline="\n")

        for existing in sorted(dest_root.rglob("*")):
            if existing.is_symlink():
                failures.append(
                    f"refuses to inspect a symbolic link in generated skill resources: {existing.relative_to(root)}"
                )
                continue
            if not existing.is_file():
                continue
            if existing in expected_destinations:
                continue
            text = existing.read_text(encoding="utf-8", errors="replace")
            if is_generated(text):
                if check:
                    failures.append(f"stale generated skill resource: {existing.relative_to(root)}")
                else:
                    existing.unlink()
            else:
                failures.append(f"non-generated skill resource not managed by sync: {existing.relative_to(root)}")

        if not check:
            for directory in sorted(
                (path for path in dest_root.rglob("*") if path.is_dir()),
                key=lambda path: len(path.parts),
                reverse=True,
            ):
                try:
                    directory.rmdir()
                except OSError:
                    pass

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        return 1

    if check:
        print("agent skill sync check passed")
    else:
        print("agent skill sync complete")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
