#!/usr/bin/env python3
"""Validate shared AI agent configuration without third-party packages."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

from sync_agent_assets import skill_files as safe_skill_files

try:
    import yaml as yaml_parser
except ModuleNotFoundError:  # Optional full parser; built-in safety checks remain mandatory.
    yaml_parser = None  # type: ignore[assignment]

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    tomllib = None  # type: ignore[assignment]

GENERATED_PREFIX = "<!-- GENERATED by .ai/scripts/sync_agent_assets.py from "
GENERATED_SUFFIX = ". DO NOT EDIT. -->"
NAME_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
SECRET_VALUE_RE = re.compile(
    r"(?i)(api[_-]?key|secret|token|password|private[_-]?key)\s*[:=]\s*['\"]?[A-Za-z0-9_./+=-]{16,}"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def starts_quoted_yaml_scalar(line: str, index: int) -> bool:
    prefix = line[:index].rstrip()
    return not prefix or prefix[-1] in "-:,[{"


def validate_yaml_text(path: Path, root: Path, errors: list[str]) -> None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        fail(errors, f"invalid YAML {path.relative_to(root)}: cannot read UTF-8 text: {exc}")
        return

    if yaml_parser is not None:
        try:
            yaml_parser.safe_load(text)
        except Exception as exc:  # noqa: BLE001
            fail(errors, f"invalid YAML {path.relative_to(root)}: parser rejected document: {exc}")

    quoted_from: int | None = None
    escaped = False
    for line_number, line in enumerate(text.splitlines(), start=1):
        index = 0
        while index < len(line):
            char = line[index]
            if quoted_from is not None:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    quoted_from = None
                index += 1
                continue

            if char == "#" and (index == 0 or line[index - 1].isspace()):
                break
            if char == '"' and starts_quoted_yaml_scalar(line, index):
                quoted_from = line_number
                index += 1
                continue
            if char == "!":
                prefix = line[:index].rstrip()
                token_boundary = not prefix or prefix[-1] in "-:,[{"
                if token_boundary and index + 1 < len(line) and not line[index + 1].isspace():
                    fail(
                        errors,
                        f"invalid YAML {path.relative_to(root)}:{line_number}: unsupported explicit tag",
                    )
            index += 1
        escaped = False

    if quoted_from is not None:
        fail(
            errors,
            f"invalid YAML {path.relative_to(root)}:{quoted_from}: unterminated double-quoted scalar",
        )


def validate_yaml_files(root: Path, errors: list[str]) -> None:
    yaml_files = [root / ".aider.conf.yml"]
    yaml_files.extend(sorted(path for path in (root / ".ai").rglob("*") if path.suffix in {".yaml", ".yml"}))
    for path in yaml_files:
        if path.is_symlink():
            fail(errors, f"invalid YAML source is a symbolic link: {path.relative_to(root)}")
            continue
        if path.is_file():
            validate_yaml_text(path, root, errors)


def required_paths() -> list[str]:
    return [
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        "CONVENTIONS.md",
        ".aider.conf.yml",
        "AI_AGENT_TEAM_GUIDE.md",
        ".ai/README.md",
        ".ai/PROMPTS.md",
        ".ai/manifest.yaml",
        ".ai/references.md",
        ".ai/core/mission.md",
        ".ai/core/instruction-precedence.md",
        ".ai/core/engineering-principles.md",
        ".ai/core/required-workflow.md",
        ".ai/core/quality-gates.md",
        ".ai/core/code-quality-intelligence.md",
        ".ai/core/memory-policy.md",
        ".ai/core/risk-model.md",
        ".ai/core/definition-of-done.md",
        ".ai/core/output-contract.md",
        ".ai/core/governed-runtime.md",
        ".ai/core/universal-action-gateway.md",
        ".ai/core/zero-trust-mcp.md",
        ".ai/context/architecture.md",
        ".ai/context/glossary.md",
        ".ai/context/repository-map.md",
        ".ai/context/build-test-commands.md",
        ".ai/context/ownership.md",
        ".ai/context/agent-roles.md",
        ".ai/context/mcp-trust-registry.yaml",
        ".ai/context/mcp-trust-registry.json",
        ".ai/rules/engineering.md",
        ".ai/rules/security.md",
        ".ai/rules/testing.md",
        ".ai/rules/api-design.md",
        ".ai/rules/database.md",
        ".ai/rules/observability.md",
        ".ai/rules/dependencies.md",
        ".ai/rules/git-and-pr.md",
        ".ai/rules/documentation.md",
        ".ai/rules/diagramming.md",
        ".ai/rules/delivery-traceability.md",
        ".ai/rules/seo-geo.md",
        ".ai/rules/visual-design-integrity.md",
        ".ai/rules/animation-integrity.md",
        ".ai/rules/human-writing-integrity.md",
        ".ai/rules/product-content-integrity.md",
        ".ai/rules/marketing-integrity.md",
        ".ai/workflows/start-task.md",
        ".ai/workflows/authorize-governed-action.md",
        ".ai/workflows/authorize-mcp-request.md",
        ".ai/workflows/repository-intelligence-workflow.md",
        ".ai/workflows/plan-existing-system-change.md",
        ".ai/workflows/implement-feature.md",
        ".ai/workflows/fix-bug.md",
        ".ai/workflows/review-pr.md",
        ".ai/workflows/investigate-incident.md",
        ".ai/workflows/database-change.md",
        ".ai/workflows/create-design-document.md",
        ".ai/workflows/prepare-pr-or-mr.md",
        ".ai/workflows/synchronize-work-item.md",
        ".ai/workflows/prepare-jira-completion-package.md",
        ".ai/workflows/build-public-website.md",
        ".ai/workflows/plan-evidence-based-marketing.md",
        ".ai/workflows/run-evidence-quality-evals.md",
        ".ai/prompts/task-contract.md",
        ".ai/prompts/existing-system-change-request.md",
        ".ai/prompts/plan-approval-response.md",
        ".ai/prompts/bug-report.md",
        ".ai/prompts/feature-request.md",
        ".ai/prompts/pr-review.md",
        ".ai/prompts/incident-investigation.md",
        ".ai/prompts/prepare-pr-or-mr.md",
        ".ai/prompts/prepare-jira-completion.md",
        ".ai/templates/jira-completion-comment.md",
        ".ai/templates/repository-intelligence-brief.md",
        ".ai/templates/change-impact-plan.md",
        ".ai/templates/implementation-approval-record.md",
        ".ai/templates/code-quality-review.md",
        ".ai/templates/memory-entry.yaml",
        ".ai/templates/demo-deck.yaml",
        ".ai/templates/demo-evidence-workbook.yaml",
        ".ai/templates/screenshot-placeholders.md",
        ".ai/templates/seo-geo-review.md",
        ".ai/templates/seo-geo-contract.schema.json",
        ".ai/templates/seo-geo-contract.example.json",
        ".ai/templates/seo-geo-measurement-plan.md",
        ".ai/templates/design-brief.md",
        ".ai/templates/design-direction.md",
        ".ai/templates/visual-design-review.md",
        ".ai/templates/product-content-review.md",
        ".ai/templates/ui-state-inventory.md",
        ".ai/templates/motion-brief.md",
        ".ai/templates/motion-contract.md",
        ".ai/templates/animation-inventory.md",
        ".ai/templates/animation-review.md",
        ".ai/templates/marketing-context.yaml",
        ".ai/templates/marketing-brief.md",
        ".ai/templates/marketing-claim-ledger.yaml",
        ".ai/templates/marketing-measurement-plan.yaml",
        ".ai/templates/marketing-experiment.md",
        ".ai/templates/marketing-review.md",
        ".ai/templates/eval-case.json",
        ".ai/templates/review-quality-fixture.json",
        ".ai/templates/pr-evidence-package.json",
        ".ai/templates/capability.json",
        ".ai/templates/evidence-bundle.json",
        ".ai/guards/policy.yaml",
        ".ai/guards/repository-intelligence-gate.yaml",
        ".ai/guards/implementation-approval-gate.yaml",
        ".ai/guards/code-quality-profile-gate.yaml",
        ".ai/guards/memory-governance.yaml",
        ".ai/guards/forbidden-paths.yaml",
        ".ai/guards/dependency-policy.yaml",
        ".ai/guards/sensitive-data-policy.yaml",
        ".ai/guards/change-risk-rules.yaml",
        ".ai/guards/capability-policy.yaml",
        ".ai/guards/sandbox-and-secrets.yaml",
        ".ai/evals/README.md",
        ".ai/evals/behavioral-cases.json",
        ".ai/evals/scorecard.yaml",
        ".ai/evals/golden-cases.yaml",
        ".ai/evals/e2e/eval-case.schema.json",
        ".ai/evals/e2e/review-quality.schema.json",
        ".ai/evals/e2e/final-implementation-review.schema.json",
        ".ai/evals/e2e/seo-geo-contract-invalid.json",
        ".ai/scripts/enforce_command_policy.py",
        ".ai/scripts/evaluate_agent_behavior.py",
        ".ai/scripts/sync_agent_assets.py",
        ".ai/scripts/validate_agent_config.py",
        ".ai/scripts/validate_implementation_approval.py",
        ".ai/scripts/validate_seo_geo_contract.py",
        ".ai/scripts/test_agent_policies.py",
        ".ai/scripts/generate_delivery_artifacts.py",
        ".ai/scripts/repository_intelligence_lib.py",
        ".ai/scripts/check-repository-intelligence.py",
        ".ai/scripts/install-repository-intelligence.py",
        ".ai/scripts/index-repository.py",
        ".ai/scripts/refresh-repository-index.py",
        ".ai/scripts/bootstrap-repository-intelligence.ps1",
        ".ai/scripts/bootstrap-repository-intelligence.sh",
        ".ai/docs/repository-intelligence-guide.md",
        ".ai/docs/agent-adapter-strategy.md",
        ".ai/docs/governed-runtime-guide.md",
        ".ai/quality-profiles/universal.yaml",
        ".ai/quality-profiles/go.yaml",
        ".ai/quality-profiles/java.yaml",
        ".ai/quality-profiles/python.yaml",
        ".ai/quality-profiles/typescript-javascript.yaml",
        ".ai/quality-profiles/frontend-html-css.yaml",
        ".ai/quality-profiles/web-app.yaml",
        ".ai/quality-profiles/seo-geo.yaml",
        ".ai/quality-profiles/visual-design.yaml",
        ".ai/quality-profiles/animation-motion.yaml",
        ".ai/quality-profiles/mobile-app.yaml",
        ".ai/quality-profiles/desktop-app.yaml",
        ".ai/quality-profiles/infrastructure.yaml",
        ".ai/quality-profiles/devops.yaml",
        ".ai/quality-profiles/api.yaml",
        ".ai/quality-profiles/database.yaml",
        ".ai/quality-profiles/concurrency.yaml",
        ".ai/quality-profiles/memory.yaml",
        ".ai/quality-profiles/governance-maturity.yaml",
        ".ai/quality-profiles/human-writing.yaml",
        ".ai/quality-profiles/product-content.yaml",
        ".ai/quality-profiles/marketing-growth.yaml",
        ".ai/skills-src/humanize-writing/SKILL.md",
        ".ai/skills-src/humanize-writing/references/ai-patterns-dictionary.md",
        ".ai/skills-src/humanize-writing/references/voices.md",
        ".ai/skills-src/write-product-content/SKILL.md",
        ".ai/skills-src/write-product-content/agents/openai.yaml",
        ".ai/skills-src/write-product-content/references/apple-human-interface-principles.md",
        ".ai/skills-src/write-product-content/references/surface-patterns.md",
        ".ai/skills-src/marketing-growth-website/SKILL.md",
        ".ai/skills-src/marketing-growth-website/references/evidence-and-measurement.md",
        ".ai/skills-src/seo-geo-website/SKILL.md",
        ".ai/skills-src/seo-geo-website/references/contract-and-measurement.md",
        ".ai/skills-src/final-implementation-review/SKILL.md",
        ".ai/skills-src/final-implementation-review/agents/openai.yaml",
        ".ai/templates/final-implementation-review.json",
        ".ai/workflows/final-implementation-review.md",
        ".mcp.json",
        ".codex/config.toml",
        ".codex/hooks.json",
        ".codex/rules/default.rules",
        ".claude/settings.json",
        ".claude/rules/shared-policy.md",
        ".github/copilot-instructions.md",
        ".cursor/rules/ai-agent-kit.mdc",
        ".amazonq/rules/ai-agent-kit.md",
        ".junie/AGENTS.md",
        ".clinerules/ai-agent-kit.md",
        ".continue/rules/ai-agent-kit.md",
    ]


def parse_frontmatter(path: Path, errors: list[str]) -> dict[str, str]:
    text = read(path)
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        fail(errors, f"{path} missing YAML frontmatter")
        return {}
    try:
        end = lines[1:].index("---") + 1
    except ValueError:
        fail(errors, f"{path} frontmatter is not closed")
        return {}
    data: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        if ":" not in line:
            fail(errors, f"{path} has unsupported frontmatter line: {line}")
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def generated_content(source_rel: str, source_text: str) -> str:
    return f"{GENERATED_PREFIX}{source_rel}{GENERATED_SUFFIX}\n\n{source_text}"


def validate_required_files(root: Path, errors: list[str]) -> None:
    for rel in required_paths():
        if not (root / rel).exists():
            fail(errors, f"required path missing: {rel}")


def validate_root_links(root: Path, errors: list[str]) -> None:
    expected_links = [
        ".ai/guards/repository-intelligence-gate.yaml",
        ".ai/workflows/repository-intelligence-workflow.md",
        ".ai/PROMPTS.md",
        ".ai/core/required-workflow.md",
        ".ai/core/quality-gates.md",
        ".ai/core/code-quality-intelligence.md",
        ".ai/core/memory-policy.md",
        ".ai/core/risk-model.md",
        ".ai/core/output-contract.md",
        ".ai/core/governed-runtime.md",
        ".ai/guards/memory-governance.yaml",
        ".ai/guards/code-quality-profile-gate.yaml",
        ".ai/guards/capability-policy.yaml",
        ".ai/templates/memory-entry.yaml",
        ".ai/templates/product-content-review.md",
        ".ai/quality-profiles/",
        ".ai/context/repository-map.md",
        ".ai/rules/",
        ".ai/workflows/",
        ".ai/skills-src/",
    ]
    for root_file in ["AGENTS.md", "CLAUDE.md"]:
        text = read(root / root_file)
        for link in expected_links:
            if link not in text:
                fail(errors, f"{root_file} does not link to {link}")


def validate_skills(root: Path, errors: list[str]) -> None:
    src_root = root / ".ai" / "skills-src"
    names: set[str] = set()
    for skill_file in sorted(src_root.glob("*/SKILL.md")):
        try:
            sources = safe_skill_files(skill_file.parent)
        except (OSError, ValueError) as exc:
            fail(errors, f"invalid canonical skill resources for {skill_file.parent.name}: {exc}")
            continue
        data = parse_frontmatter(skill_file, errors)
        name = data.get("name", "")
        description = data.get("description", "")
        if not name:
            fail(errors, f"{skill_file} missing name")
        elif not NAME_RE.fullmatch(name):
            fail(errors, f"{skill_file} name must be lowercase hyphenated: {name}")
        elif name in names:
            fail(errors, f"duplicate skill name: {name}")
        names.add(name)
        if not description:
            fail(errors, f"{skill_file} missing description")
        if skill_file.parent.name != name:
            fail(errors, f"{skill_file} folder name must match frontmatter name {name}")

        for source in sources:
            source_rel = source.relative_to(root).as_posix()
            expected = generated_content(source_rel, read(source))
            resource_rel = source.relative_to(skill_file.parent)
            for dest_root in [
                root / ".agents" / "skills",
                root / ".claude" / "skills",
                root / ".cursor" / "skills",
                root / ".windsurf" / "skills",
                root / ".cline" / "skills",
                root / ".github" / "skills",
            ]:
                dest = dest_root / name / resource_rel
                if not dest.exists():
                    fail(errors, f"missing generated skill resource: {dest.relative_to(root)}")
                elif read(dest) != expected:
                    fail(errors, f"generated skill resource drift: {dest.relative_to(root)}")


def validate_json_toml(root: Path, errors: list[str]) -> None:
    for json_file in [
        root / ".codex" / "hooks.json",
        root / ".claude" / "settings.json",
        root / ".mcp.json",
        root / ".ai" / "context" / "mcp-trust-registry.json",
        root / ".ai" / "templates" / "seo-geo-contract.schema.json",
        root / ".ai" / "templates" / "seo-geo-contract.example.json",
        root / ".ai" / "evals" / "e2e" / "seo-geo-contract-invalid.json",
    ]:
        try:
            json.loads(read(json_file))
        except Exception as exc:  # noqa: BLE001
            fail(errors, f"invalid JSON {json_file.relative_to(root)}: {exc}")

    toml_files = [root / ".codex" / "config.toml", *sorted((root / ".codex" / "agents").glob("*.toml"))]
    if tomllib is None:
        fail(errors, "Python 3.11+ tomllib is required to validate TOML files")
        return
    for toml_file in toml_files:
        try:
            tomllib.loads(read(toml_file))
        except Exception as exc:  # noqa: BLE001
            fail(errors, f"invalid TOML {toml_file.relative_to(root)}: {exc}")


def validate_manifest_paths(root: Path, errors: list[str]) -> None:
    manifest = read(root / ".ai" / "manifest.yaml")
    for rel in re.findall(r'"(\.ai/[^"]+)"', manifest):
        if any(ch in rel for ch in "*?"):
            continue
        if not (root / rel).exists():
            fail(errors, f"manifest references missing path: {rel}")


def validate_hooks(root: Path, errors: list[str]) -> None:
    hooks_file = root / ".codex" / "hooks.json"
    try:
        hooks = json.loads(read(hooks_file))
    except Exception:
        return
    commands: list[str] = []
    for groups in hooks.get("hooks", {}).values():
        for group in groups:
            for hook in group.get("hooks", []):
                command = hook.get("command", "")
                command_windows = hook.get("commandWindows", "")
                if command:
                    commands.append(command)
                if command_windows:
                    commands.append(command_windows)
    for command in commands:
        lowered = command.lower()
        if any(term in lowered for term in ["curl ", "wget ", "invoke-webrequest", "http://", "https://", "iex "]):
            fail(errors, f"hook command appears to use network or download execution: {command}")
        match = re.search(r"(\.ai[\\/ ]scripts[\\/][A-Za-z0-9_.-]+\.(?:py|mjs))", command)
        if match:
            rel = match.group(1).replace(" ", "/").replace("\\", "/")
            if not (root / rel).exists():
                fail(errors, f"hook references missing script: {rel}")
    joined = "\n".join(commands)
    if "bootstrap-repository-intelligence" not in joined and "check-repository-intelligence" not in joined:
        fail(errors, "session hooks do not invoke the Repository Intelligence Gate")
    if "validate_implementation_approval.py --hook" not in joined:
        fail(errors, "pre-tool hooks do not enforce tracked implementation approval")
    if "enforce_command_policy.py --hook" not in joined:
        fail(errors, "pre-tool hooks do not enforce command policy")
    if "governed_action_gateway.mjs" not in joined:
        fail(errors, "pre-tool hooks do not invoke the universal action gateway")


def validate_delivery_templates(root: Path, errors: list[str]) -> None:
    template_expectations = {
        ".ai/templates/jira-completion-comment.md": ["Repository intelligence", "RCA", "Solution", "MR/PR", "Acceptance criteria", "Validation", "Docs/specs/diagrams", "Demo package", "Screenshot Placeholders"],
        ".ai/templates/change-impact-plan.md": [
            "Repository Intelligence Gate",
            "Indexed Facts",
            "Source-Code Verified Facts",
            "Problem Statement",
            "Current Behavior",
            "Change Area Boundary",
            "Impact Boundary",
            "Files Explicitly Approved For Change",
            "Areas Requiring Developer Review Before Touching",
            "Reason No Other Area Is Changed",
            "Approval Decision Requested",
        ],
        ".ai/templates/implementation-approval-record.md": ["Repository intelligence gate status", "Indexed analysis reviewed", "Approval status", "Approver", "Approved scope", "Approved paths", "Delta approval required"],
        ".ai/templates/code-quality-review.md": ["Detected Stack", "Application/platform/domain", "Selected Quality Profiles", "Platform/domain profiles", "Quality Checks", "Language/version best practices", "Platform/domain best practices", "Database connection and transaction safety", "Concurrency/deadlock/leak risk", "Heap/resource memory risk", "Release/deployment safety"],
        ".ai/templates/memory-entry.yaml": ["schema_version: 3", "title:", "category:", "scope:", "content:", "provenance:", "confidence:", "status:", "approver:", "review_date:"],
        ".ai/templates/repository-intelligence-brief.md": ["Gate Status", "Indexed Facts", "Source-Code Verified Facts", "Relevant Modules", "Entry Points And Call Paths", "Potential Impact Areas"],
        ".ai/templates/demo-deck.yaml": ["required_slides", "Manual screenshot placeholders"],
        ".ai/templates/demo-evidence-workbook.yaml": ["required_worksheets", "Screenshot Placeholders"],
        ".ai/templates/screenshot-placeholders.md": ["Placeholder ID", "Exact screen or evidence"],
        ".ai/templates/seo-geo-review.md": ["Mode And Scope", "Evidence And Limitations", "Contract Validation", "Discovery Contract", "Signal Consistency", "Crawler And Usage Policy", "Provider Surface Registry", "Structured Data And Entity Integrity", "Content And Claim Integrity", "Measurement Summary", "Claims Boundary"],
        ".ai/templates/seo-geo-measurement-plan.md": ["Scope And Decision", "Baseline And Change Boundary", "Technical eligibility", "AI Probe Protocol", "Privacy, Consent, And Access", "Decision Rule", "Claims Boundary"],
        ".ai/templates/design-brief.md": ["Product Surface", "Audience And Outcome", "Content And Information Architecture", "Brand And Assets", "References", "Constraints", "Unknowns And Approval Needs"],
        ".ai/templates/design-direction.md": ["Design Read", "Direction Controls", "Principles And Anti-Goals", "Inspiration Boundary", "Design System", "Responsive Composition", "State Coverage", "Approval Boundary"],
        ".ai/templates/visual-design-review.md": ["Scope And Direction", "Evidence", "Findings", "System Consistency", "Interaction And State Coverage", "Responsive And Inclusive Design", "Performance And Delivery"],
        ".ai/templates/ui-state-inventory.md": ["Default", "Focus", "Loading", "Empty", "Error/recovery", "Success", "Responsive notes", "Evidence"],
        ".ai/templates/motion-brief.md": ["Surface And Context", "Animation Decision", "Interaction And Lifecycle", "Accessibility And Fallback", "Performance And Compatibility", "Scope And Approval"],
        ".ai/templates/motion-contract.md": ["Token or pattern", "Interrupt/cancel behavior", "Reduced motion", "Runtime Contract", "Accessibility And Static Equivalence", "Performance And Compatibility Budget"],
        ".ai/templates/animation-inventory.md": ["Trigger", "Purpose", "Frequency", "Interruptible", "Reduced motion", "Cleanup/lifecycle", "Evidence", "Action"],
        ".ai/templates/animation-review.md": ["Scope And Environment", "Evidence", "Findings", "Decision And Timing", "Interruptibility, Gesture, And Lifecycle", "Accessibility", "Performance And Compatibility"],
    }
    for rel, fragments in template_expectations.items():
        text = read(root / rel)
        for fragment in fragments:
            if fragment not in text:
                fail(errors, f"{rel} missing required section or fragment: {fragment}")

    policy_text = read(root / ".ai" / "guards" / "implementation-approval-gate.yaml")
    for fragment in ["fail-closed", "approval_evidence_required", "outside_approved_scope", "agent_self_authorization_allowed: false"]:
        if fragment not in policy_text:
            fail(errors, f"implementation approval gate missing: {fragment}")


def validate_team_ready_governance(root: Path, errors: list[str]) -> None:
    output_contract = read(root / ".ai" / "core" / "output-contract.md")
    for fragment in [
        "Summary",
        "Context reviewed",
        "Root cause / rationale",
        "Changes made",
        "Files changed",
        "Tests executed",
        "Validation results",
        "Compatibility impact",
        "Security and performance considerations",
        "Assumptions",
        "Remaining risks",
        "Memory candidates",
    ]:
        if fragment not in output_contract:
            fail(errors, f"output contract missing section: {fragment}")

    quality_gates = read(root / ".ai" / "core" / "quality-gates.md")
    for fragment in [
        "PASSED",
        "FAILED",
        "NOT_APPLICABLE",
        "NOT_RUN",
        "Compilation passed",
        "Unit tests passed",
        "Integration tests passed where applicable",
        "Static analysis passed",
        "Architecture checks passed",
        "Platform/domain quality profile selected",
        "Security checks passed",
        "Database migration validated",
        "API compatibility reviewed",
        "Observability impact reviewed",
        "Diff self-reviewed",
        "Product content profile selected",
        "Product language meaning",
        "Evidence command/result",
    ]:
        if fragment not in quality_gates:
            fail(errors, f"quality gates missing required fragment: {fragment}")

    role_text = read(root / ".ai" / "context" / "agent-roles.md")
    guide_text = read(root / "AI_AGENT_TEAM_GUIDE.md")
    for role in ["Module Context Owner", "Memory Approver", "Skill Maintainer", "Quarterly Review"]:
        if role not in role_text:
            fail(errors, f"agent governance role missing: {role}")
        if role not in guide_text:
            fail(errors, f"team guide governance role missing: {role}")

    for fragment in [
        "Persona Composition Matrix",
        "Solution Architect",
        "Senior Backend Engineer",
        "Production SRE",
        "Security Engineer",
        "QA Lead",
        "Release Manager",
        "Tech Lead",
        "architecture-review",
        "performance-investigation",
        "observability-review",
        "security-review",
        "threat-model",
        "test-strategy",
        "release-readiness",
        "repository-health",
    ]:
        if fragment not in role_text:
            fail(errors, f"agent persona composition missing from role map: {fragment}")
        if fragment not in guide_text:
            fail(errors, f"agent persona composition missing from team guide: {fragment}")

    if "write-product-content" not in guide_text:
        fail(errors, "team guide missing mandatory product content skill")

    memory_policy = read(root / ".ai" / "core" / "memory-policy.md")
    for fragment in [
        "Allowed Memory Categories",
        "Denied Memory Categories",
        "Title",
        "Category",
        "Scope",
        "Content",
        "Source",
        "Confidence",
        "Status",
        "Approver",
        "Review date",
        "Current source code",
        "Tests",
        "Approved architecture docs",
        "Approved memory",
        "Historical discussion",
        "Agent inference",
        "at most 5 entries",
        "never more than 10 entries",
        "confidence `>= 0.8`",
    ]:
        if fragment not in memory_policy:
            fail(errors, f"memory policy missing required fragment: {fragment}")

    memory_guard = read(root / ".ai" / "guards" / "memory-governance.yaml")
    for fragment in [
        "default_retrieval: \"approved-only\"",
        "approval_required: true",
        "APPROVED",
        "PROPOSED",
        "STALE",
        "preferred_minimum: 0.8",
        "default_max_entries: 5",
        "absolute_max_entries: 10",
        "pii",
        "secrets",
        "production_customer_data",
        "cadence: \"quarterly\"",
    ]:
        if fragment not in memory_guard:
            fail(errors, f"memory governance guard missing required fragment: {fragment}")

    policy_text = read(root / ".ai" / "guards" / "policy.yaml")
    for fragment in ["quality_gates:", "memory_governance:", "max_entries_default: 5", "max_entries_absolute: 10"]:
        if fragment not in policy_text:
            fail(errors, f"policy guard missing required fragment: {fragment}")

    database_rules = read(root / ".ai" / "rules" / "database.md")
    for fragment in [
        "Do not call `repository.save()` inside large loops.",
        "batch update",
        "bulk persistence",
        "transaction size",
        "flush/clear behavior",
        "locking risk",
    ]:
        if fragment not in database_rules:
            fail(errors, f"database rules missing developer correction rule fragment: {fragment}")

    human_writing_rules = read(root / ".ai" / "rules" / "human-writing-integrity.md")
    for fragment in [
        "Preserve Substance",
        "task-scoped data",
        "Do not promise to evade AI detectors",
        "Do not remove attribution",
    ]:
        if fragment not in human_writing_rules:
            fail(errors, f"human writing rules missing required fragment: {fragment}")

    product_content_rules = read(root / ".ai" / "rules" / "product-content-integrity.md")
    for fragment in [
        "Apply The Human Interface Quality Bar",
        "Purpose",
        "Agency",
        "Responsibility",
        "Preserve Platform Integrity",
        "Preserve Meaning And Trust",
        "Write Like A Helpful Person",
        "Preserve Data Semantics",
        "Protect Accessibility And Localization",
        "Block final success",
    ]:
        if fragment not in product_content_rules:
            fail(errors, f"product content rules missing required fragment: {fragment}")

    product_content_skill = read(root / ".ai" / "skills-src" / "write-product-content" / "SKILL.md")
    for fragment in [
        "Run The Product Language Gate",
        "Establish The Context Contract",
        "Apply The Mandatory Human Interface Principles",
        "apple-human-interface-principles.md",
        "target-platform conventions",
        "Preserve Data Semantics",
        "Verify In The Real Experience",
        "Return `BLOCKED`",
        "product-content-review.md",
    ]:
        if fragment not in product_content_skill:
            fail(errors, f"product content skill missing required fragment: {fragment}")

    apple_hig_reference = read(root / ".ai" / "skills-src" / "write-product-content" / "references" / "apple-human-interface-principles.md")
    for fragment in [
        "Scope Boundary",
        "Mandatory Principle Mapping",
        "Purpose",
        "Agency",
        "Responsibility",
        "Familiarity",
        "Flexibility",
        "Simplicity",
        "Craft",
        "Delight",
        "Platform-Fit Decision",
        "Official Sources",
        "developer.apple.com/design/human-interface-guidelines/writing",
    ]:
        if fragment not in apple_hig_reference:
            fail(errors, f"Apple Human Interface reference missing required fragment: {fragment}")

    product_content_template = read(root / ".ai" / "templates" / "product-content-review.md")
    for fragment in [
        "Content Inventory",
        "State Coverage",
        "Data Semantics",
        "Mandatory Human Interface Principles",
        "Platform Fit",
        "Purpose",
        "Delight",
        "Natural, respectful tone",
        "Accessibility",
        "Localization and text expansion",
        "Product Language Gate",
    ]:
        if fragment not in product_content_template:
            fail(errors, f"product content review template missing required fragment: {fragment}")

    marketing_skill = read(root / ".ai" / "skills-src" / "marketing-growth-website" / "SKILL.md")
    for fragment in [
        "`discover`",
        "`plan`",
        "`implement`",
        "`experiment`",
        "`measure`",
        "`audit`",
        "NOT_MEASURED",
        "marketing-measurement-plan.yaml",
        "Protected external actions",
    ]:
        if fragment not in marketing_skill:
            fail(errors, f"marketing growth skill missing required fragment: {fragment}")

    marketing_rules = read(root / ".ai" / "rules" / "marketing-integrity.md")
    for fragment in [
        "Never fabricate",
        "NOT_MEASURED",
        "dark patterns",
        "minimum data",
        "governed action gateway",
        "competitor and campaign references",
    ]:
        if fragment not in marketing_rules:
            fail(errors, f"marketing integrity rules missing required fragment: {fragment}")

    golden_cases = read(root / ".ai" / "evals" / "golden-cases.yaml")
    for case_id in [
        "repository-save-in-loop",
        "memory-candidate-approval",
        "memory-retrieval-bounded",
        "cross-area-change-without-approval",
        "humanize-preserves-claims",
        "humanize-no-fabricated-specificity",
        "humanize-detector-request",
        "humanize-voice-sample-privacy",
        "product-content-context-before-copy",
        "product-content-action-label",
        "product-content-error-recovery",
        "product-content-state-completeness",
        "product-content-data-semantics",
        "product-content-accessibility-localization",
        "product-content-no-fabricated-business-context",
        "product-content-mandatory-composition",
        "product-content-human-interface-principles",
        "product-content-agency-and-recovery",
        "product-content-responsible-permission",
        "product-content-platform-fit",
        "product-content-alert-restraint",
        "product-content-onboarding-and-help",
        "product-content-delight-subordinate",
        "product-content-current-hig-evidence",
        "marketing-context-missing",
        "fabricated-marketing-proof",
        "marketing-missing-baseline",
        "low-traffic-experiment",
        "invasive-marketing-tracking",
        "marketing-external-action-boundary",
        "marketing-dark-pattern",
        "regulated-marketing-claim",
    ]:
        if case_id not in golden_cases:
            fail(errors, f"golden cases missing required case: {case_id}")


def validate_code_quality_profiles(root: Path, errors: list[str]) -> None:
    core_text = read(root / ".ai" / "core" / "code-quality-intelligence.md")
    for fragment in [
        "language, version, framework",
        "selected quality profiles",
        "connection leaks",
        "deadlocks",
        "heap",
        "platform-aware",
        "platform/domain profiles",
    ]:
        if fragment not in core_text:
            fail(errors, f"code quality intelligence missing required fragment: {fragment}")

    guard_text = read(root / ".ai" / "guards" / "code-quality-profile-gate.yaml")
    for fragment in [
        "code-quality-profile-gate",
        "fail-closed",
        "select_platform_or_domain_profiles",
        "platform_domain_best_practices",
        "database_connection_leaks",
        "deadlock_risk",
        "heap_memory_leaks",
    ]:
        if fragment not in guard_text:
            fail(errors, f"code quality profile gate missing required fragment: {fragment}")

    profiles = {
        "universal.yaml": ["id: universal", "clean code", "resource cleanup"],
        "go.yaml": ["id: go", "go test ./...", "goroutine leaks are prevented"],
        "java.yaml": ["id: java", "repository.save", "thread pool", "heap retention"],
        "python.yaml": ["id: python", "pytest", "async", "session, transaction, cursor, and connection lifecycle"],
        "typescript-javascript.yaml": ["id: typescript-javascript", "tsc --noEmit", "event-loop", "Promise"],
        "frontend-html-css.yaml": ["id: frontend-html-css", "accessibility", "bundle"],
        "web-app.yaml": ["id: web-app", "Core Web Vitals", "XSS", "accessibility"],
        "seo-geo.yaml": ["id: seo-geo", "truth", "validate_seo_geo_contract.py", "canonical graphs", "crawler_and_provider_policy", "integrity guardrails", "fail closed"],
        "mobile-app.yaml": ["id: mobile-app", "application lifecycle", "permissions", "battery"],
        "desktop-app.yaml": ["id: desktop-app", "code signing", "auto-update", "native resource cleanup"],
        "infrastructure.yaml": ["id: infrastructure", "terraform plan", "least privilege", "drift"],
        "devops.yaml": ["id: devops", "CI/CD", "release gates", "supply chain"],
        "api.yaml": ["id: api", "backward compatibility", "idempotency"],
        "database.yaml": ["id: database", "connection leaks prevented", "transaction"],
        "concurrency.yaml": ["id: concurrency", "deadlock", "task/thread/goroutine lifecycle"],
        "memory.yaml": ["id: memory", "heap retention", "resource cleanup"],
        "human-writing.yaml": ["id: human-writing", "meaning_preservation", "voice_fidelity", "authorship"],
        "product-content.yaml": ["id: product-content", "human_interface_principles", "platform_fit", "meaning_and_behavior", "data_semantics", "accessibility", "localization", "blocked_when"],
        "marketing-growth.yaml": ["id: marketing-growth", "claims_and_proof", "measurement", "authorization"],
    }
    profile_root = root / ".ai" / "quality-profiles"
    for filename, fragments in profiles.items():
        path = profile_root / filename
        if not path.exists():
            fail(errors, f"quality profile missing: {path.relative_to(root)}")
            continue
        text = read(path)
        for fragment in fragments:
            if fragment not in text:
                fail(errors, f"{path.relative_to(root)} missing required fragment: {fragment}")


def validate_prompt_catalog(root: Path, errors: list[str]) -> None:
    catalog = read(root / ".ai" / "PROMPTS.md")
    for prompt_name in [
        "start-task",
        "plan-change",
        "implement-approved",
        "fix-bug",
        "code-quality-review",
        "review-pr",
        "investigate-incident",
        "prepare-handoff",
    ]:
        if f"## {prompt_name}" not in catalog:
            fail(errors, f"prompt catalog missing prompt: {prompt_name}")
        if f"`{prompt_name}`" not in catalog:
            fail(errors, f"prompt catalog missing prompt table entry: {prompt_name}")
    for fragment in [
        "npx --yes @hunpeolabs/ai-agent-kit@latest bootstrap --yes",
        "npx --yes @hunpeolabs/ai-agent-kit@latest prompts",
        "npx --yes @hunpeolabs/ai-agent-kit@latest prompt start-task",
        "Do not edit files yet",
        "quality gates",
        "code-quality-review",
        "selected `.ai/quality-profiles/`",
        "memory candidates",
    ]:
        if fragment not in catalog:
            fail(errors, f"prompt catalog missing required fragment: {fragment}")


def validate_seo_geo_assets(root: Path, errors: list[str]) -> None:
    rule = read(root / ".ai" / "rules" / "seo-geo.md")
    for fragment in [
        "Truth Contract",
        "Discovery Consistency",
        "Signal And Security Precedence",
        "Crawler And Provider Policy",
        "Measurement And Effectiveness",
        "VERIFIED",
        "QUALIFIED",
        "provider-specific",
    ]:
        if fragment not in rule:
            fail(errors, f"SEO/GEO rule missing required fragment: {fragment}")

    skill = read(root / ".ai" / "skills-src" / "seo-geo-website" / "SKILL.md")
    for fragment in [
        "contract-and-measurement.md",
        "validate_seo_geo_contract.py",
        "stable entities",
        "AI visibility",
        "INCONCLUSIVE",
        "generated skill resources",
    ]:
        if fragment not in skill:
            fail(errors, f"SEO/GEO skill missing required fragment: {fragment}")

    validator = root / ".ai" / "scripts" / "validate_seo_geo_contract.py"
    valid = root / ".ai" / "templates" / "seo-geo-contract.example.json"
    invalid = root / ".ai" / "evals" / "e2e" / "seo-geo-contract-invalid.json"
    valid_result = subprocess.run(
        [sys.executable, "-B", str(validator), str(valid)],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if valid_result.returncode != 0:
        fail(errors, f"valid SEO/GEO contract fixture failed: {valid_result.stderr.strip()}")
    invalid_result = subprocess.run(
        [sys.executable, "-B", str(validator), str(invalid)],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if invalid_result.returncode == 0:
        fail(errors, "invalid SEO/GEO contract fixture unexpectedly passed")
    for fragment in [
        "redirect routes must be non-indexable",
        "references unknown id",
        "is stale as of",
        "claim 'claim:stale' is not publishable",
        "must be omitted unless status is MEASURED",
    ]:
        if fragment not in invalid_result.stderr:
            fail(errors, f"invalid SEO/GEO contract fixture missing regression evidence: {fragment}")


def validate_agent_adapter_strategy(root: Path, errors: list[str]) -> None:
    strategy = read(root / ".ai" / "docs" / "agent-adapter-strategy.md")
    for fragment in [
        "Claude Code",
        "OpenAI Codex",
        "GitHub Copilot",
        "Cursor",
        "Windsurf",
        "Gemini CLI",
        "Amazon Q Developer",
        "JetBrains Junie",
        "Cline",
        "Devin",
        "Aider",
        "Continue",
        "Adapter Contract",
        "Route the agent to `.ai/`",
        "Keep bootstrap local-only",
    ]:
        if fragment not in strategy:
            fail(errors, f"agent adapter strategy missing required fragment: {fragment}")


def validate_native_adapters(root: Path, errors: list[str]) -> None:
    adapter_files = [
        ".github/copilot-instructions.md",
        ".cursor/rules/ai-agent-kit.mdc",
        "GEMINI.md",
        ".amazonq/rules/ai-agent-kit.md",
        ".junie/AGENTS.md",
        ".clinerules/ai-agent-kit.md",
        "CONVENTIONS.md",
        ".continue/rules/ai-agent-kit.md",
    ]
    for rel in adapter_files:
        text = read(root / rel)
        for fragment in [".ai/", "approval", "quality"]:
            if fragment.lower() not in text.lower():
                fail(errors, f"{rel} missing adapter contract fragment: {fragment}")

    cursor = parse_frontmatter(root / ".cursor" / "rules" / "ai-agent-kit.mdc", errors)
    if cursor.get("alwaysApply") != "true":
        fail(errors, "Cursor adapter must always apply the shared contract")

    continuation = parse_frontmatter(root / ".continue" / "rules" / "ai-agent-kit.md", errors)
    if continuation.get("alwaysApply") != "true":
        fail(errors, "Continue adapter must always apply the shared contract")

    aider = read(root / ".aider.conf.yml")
    for fragment in ["read:", "CONVENTIONS.md"]:
        if fragment not in aider:
            fail(errors, f"Aider adapter missing: {fragment}")

    gemini = read(root / "GEMINI.md")
    if "@./.ai/core/required-workflow.md" not in gemini:
        fail(errors, "Gemini adapter must import the required workflow")


def validate_repository_intelligence(root: Path, errors: list[str], quick: bool) -> None:
    guard_text = read(root / ".ai" / "guards" / "repository-intelligence-gate.yaml")
    for fragment in [
        "@colbymchenry/codegraph",
        "cocoindex-code[full]",
        ".git/**",
        "**/node_modules/**",
        "**/target/**",
        "**/.env",
        "**/*.pem",
        "**/*cvv*",
        "**/*pan*",
        "compare_index_metadata_to_current_git_commit",
        "run_codegraph_health_query",
        "run_cocoindex_health_query",
        "preferred-with-degraded-fallback",
        "bounded native inspection",
    ]:
        if fragment not in guard_text:
            fail(errors, f"repository intelligence gate missing: {fragment}")

    for root_file in ["AGENTS.md", "CLAUDE.md", "AI_AGENT_TEAM_GUIDE.md"]:
        text = read(root / root_file)
        for fragment in ["Repository Intelligence Gate", "CodeGraph", "CocoIndex", "DEGRADED"]:
            if fragment not in text:
                fail(errors, f"{root_file} missing repository intelligence fragment: {fragment}")

    role_text = read(root / ".ai" / "context" / "agent-roles.md")
    required_roles = [
        "Team Lead Orchestrator",
        "Domain Analyst",
        "Impact Explorer",
        "Solution Architect",
        "Senior Backend Engineer",
        "Production SRE",
        "Security Engineer",
        "Tech Lead",
        "Implementation Engineer",
        "Database/Data Engineer",
        "Integration Engineer",
        "UI/UX Lead",
        "QA Lead",
        "Security Reviewer",
        "SRE/Release Engineer",
        "Release Manager",
        "Documentation Delivery Agent",
        "Independent Code Reviewer",
        "Module Context Owner",
        "Memory Approver",
        "Skill Maintainer",
        "Quarterly Review",
    ]
    for role in required_roles:
        if role not in role_text:
            fail(errors, f"agent role map missing role: {role}")
    if "repository-intelligence" not in role_text:
        fail(errors, "agent role map does not reference repository-intelligence skill")

    for agent_file in [*sorted((root / ".codex" / "agents").glob("*.toml")), *sorted((root / ".claude" / "agents").glob("*.md"))]:
        text = read(agent_file)
        if "repository-intelligence" not in text:
            fail(errors, f"agent role does not reference repository-intelligence skill: {agent_file.relative_to(root)}")

    plan_text = read(root / ".ai" / "workflows" / "plan-existing-system-change.md")
    for fragment in ["Repository Intelligence Gate", "Query CodeGraph", "Query CocoIndex", "repository intelligence brief"]:
        if fragment not in plan_text:
            fail(errors, f"plan workflow missing indexed impact analysis fragment: {fragment}")

    implement_text = read(root / ".ai" / "workflows" / "implement-feature.md")
    for fragment in ["Run the Repository Intelligence Gate", "Verify explicit approval evidence", "refresh CodeGraph/CocoIndex indexes"]:
        if fragment not in implement_text:
            fail(errors, f"implementation workflow missing gate fragment: {fragment}")

    required_workflow = read(root / ".ai" / "core" / "required-workflow.md")
    for fragment in ["Run the Repository Intelligence Gate", "Query CodeGraph", "refresh CodeGraph/CocoIndex indexes"]:
        if fragment not in required_workflow:
            fail(errors, f"required workflow missing repository intelligence fragment: {fragment}")

    mcp_text = read(root / ".mcp.json")
    if "codegraph" not in mcp_text or "cocoindex-code" not in mcp_text:
        fail(errors, ".mcp.json must configure codegraph and cocoindex-code")

    if quick:
        return

    result = subprocess.run(
        [
            sys.executable,
            "-B",
            str(root / ".ai" / "scripts" / "check-repository-intelligence.py"),
            "--json",
        ],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        timeout=240,
    )
    if result.returncode != 0:
        fail(errors, f"Repository Intelligence Gate check failed: {result.stderr.strip() or result.stdout.strip()}")
        return
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        fail(errors, f"Repository Intelligence Gate JSON invalid: {exc}")
        return
    mode = payload.get("mode")
    if mode not in {"READY", "DEGRADED"}:
        fail(errors, f"Repository Intelligence Gate returned unsupported mode: {mode!r}")


def validate_delivery_artifact_generator(root: Path, errors: list[str]) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp) / "artifacts"
        result = subprocess.run(
            [
                sys.executable,
                str(root / ".ai" / "scripts" / "generate_delivery_artifacts.py"),
                "--jira-key",
                "DEMO-000",
                "--title",
                "Validation Artifact",
                "--output-dir",
                str(out_dir),
                "--json",
            ],
            cwd=root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode != 0:
            fail(errors, f"delivery artifact generator failed: {result.stderr.strip() or result.stdout.strip()}")
            return
        try:
            payload = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            fail(errors, f"delivery artifact generator did not emit JSON: {exc}")
            return
        required_keys = {"summary", "pptx", "xlsx", "screenshot_placeholders"}
        if set(payload) != required_keys:
            fail(errors, f"delivery artifact generator emitted wrong keys: {sorted(payload)}")
            return
        for label, artifact_path in payload.items():
            path = Path(artifact_path)
            if not path.exists() or path.stat().st_size == 0:
                fail(errors, f"generated {label} artifact missing or empty: {path}")

        summary_text = Path(payload["summary"]).read_text(encoding="utf-8")
        if "DEMO-000" not in summary_text or "Validation Artifact" not in summary_text or "SS-01" not in summary_text:
            fail(errors, "generated Jira summary missing key, title, or screenshot placeholder")

        with zipfile.ZipFile(payload["pptx"]) as deck:
            names = set(deck.namelist())
            for required in ["ppt/presentation.xml", "ppt/slides/slide1.xml", "ppt/slides/slide6.xml"]:
                if required not in names:
                    fail(errors, f"generated PPTX missing {required}")
            slide_text = deck.read("ppt/slides/slide1.xml").decode("utf-8", errors="replace")
            if "DEMO-000" not in slide_text or "Validation Artifact" not in slide_text:
                fail(errors, "generated PPTX missing Jira key or title")

        with zipfile.ZipFile(payload["xlsx"]) as book:
            names = set(book.namelist())
            for required in ["xl/workbook.xml", "xl/worksheets/sheet1.xml", "xl/worksheets/sheet5.xml"]:
                if required not in names:
                    fail(errors, f"generated XLSX missing {required}")
            sheet_text = book.read("xl/worksheets/sheet1.xml").decode("utf-8", errors="replace")
            if "DEMO-000" not in sheet_text or "Validation Artifact" not in sheet_text:
                fail(errors, "generated XLSX missing Jira key or title")


def validate_secret_like_values(root: Path, errors: list[str]) -> None:
    scan_roots = [
        root / "AGENTS.md",
        root / "CLAUDE.md",
        root / "GEMINI.md",
        root / "CONVENTIONS.md",
        root / ".aider.conf.yml",
        root / "AI_AGENT_TEAM_GUIDE.md",
        root / ".ai",
        root / ".agents",
        root / ".codex",
        root / ".claude",
        root / ".github",
        root / ".cursor",
        root / ".windsurf",
        root / ".amazonq",
        root / ".junie",
        root / ".cline",
        root / ".clinerules",
        root / ".continue",
    ]
    files: list[Path] = []
    for item in scan_roots:
        if item.is_file():
            files.append(item)
        elif item.is_dir():
            files.extend(path for path in item.rglob("*") if path.is_file())
    for path in files:
        text = read(path)
        if SECRET_VALUE_RE.search(text):
            fail(errors, f"secret-like value found in {path.relative_to(root)}")


def validate_instruction_budgets(root: Path, errors: list[str]) -> None:
    budgets = {
        "AGENTS.md": 32 * 1024,
        "CLAUDE.md": 32 * 1024,
        "GEMINI.md": 8 * 1024,
        "CONVENTIONS.md": 8 * 1024,
    }
    for rel, limit in budgets.items():
        size = (root / rel).stat().st_size
        if size > limit:
            fail(errors, f"{rel} exceeds {limit} byte budget: {size}")


def validate_codex_rules_available(root: Path, errors: list[str], quick: bool) -> None:
    rules = root / ".codex" / "rules" / "default.rules"
    text = read(rules)
    for required in ["prefix_rule(", "match = [", "not_match = [", "decision = \"forbidden\"", "decision = \"prompt\""]:
        if required not in text:
            fail(errors, f"Codex rules file missing expected syntax: {required}")
    if quick:
        return
    codex = shutil.which("codex")
    if not codex:
        print("codex CLI unavailable; static .rules checks used as documented fallback")
        return
    result = subprocess.run(
        [codex, "execpolicy", "check", "--rules", str(rules), "--", "git", "status"],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        fail(errors, f"codex execpolicy check failed: {result.stderr.strip() or result.stdout.strip()}")


def validate_governed_runtime(root: Path, errors: list[str]) -> None:
    runtime = read(root / ".ai" / "core" / "governed-runtime.md")
    for fragment in ["DISCOVER", "PLAN_READY", "APPROVED", "IMPLEMENTING", "VERIFYING", "REVIEW_READY", "RELEASED", "allow", "ask", "deny"]:
        if fragment not in runtime:
            fail(errors, f"governed runtime missing contract fragment: {fragment}")
    capability = read(root / ".ai" / "guards" / "capability-policy.yaml")
    for fragment in ["expires_at", "max_actions", "approval_hash", "CRITICAL_AUTONOMOUS_EXECUTION_FORBIDDEN"]:
        if fragment not in capability:
            fail(errors, f"capability policy missing fragment: {fragment}")
    registry = read(root / ".ai" / "context" / "mcp-trust-registry.yaml")
    for fragment in ["default_trust: deny", "executable_or_image_digest", "review_expires"]:
        if fragment not in registry:
            fail(errors, f"MCP trust registry missing fragment: {fragment}")
    gateway = read(root / ".ai" / "core" / "universal-action-gateway.md")
    gateway_normalized = " ".join(gateway.lower().split())
    for fragment in ["normalized action envelope", "allow", "ask", "deny", "decision token", "fail closed"]:
        if fragment.lower() not in gateway_normalized:
            fail(errors, f"universal action gateway missing contract fragment: {fragment}")
    broker = read(root / ".ai" / "core" / "zero-trust-mcp.md")
    broker_normalized = " ".join(broker.lower().split())
    for fragment in ["exact identity", "credential", "SSRF", "prompt injection", "rate limit"]:
        if fragment.lower() not in broker_normalized:
            fail(errors, f"zero-trust MCP contract missing fragment: {fragment}")
    try:
        registry_json = json.loads(read(root / ".ai" / "context" / "mcp-trust-registry.json"))
    except Exception:
        registry_json = {}
    if registry_json.get("default_trust") != "deny":
        fail(errors, "JSON MCP trust registry must be deny-by-default")
    report = read(root / ".ai" / "core" / "task-completion-report.md")
    report_normalized = " ".join(report.lower().split())
    for fragment in [
        "weighted acceptance-criterion progress",
        "production readiness",
        "token usage",
        "api-equivalent estimated cost",
        "fail-open",
        "fail-closed",
    ]:
        if fragment.lower() not in report_normalized:
            fail(errors, f"task completion report missing contract fragment: {fragment}")
    finalizer = read(root / ".ai" / "scripts" / "final_task_report.mjs")
    for fragment in ["AI_AGENT_KIT_TASK_ID", "buildFinalTaskReport", "renderFinalTaskReport"]:
        if fragment not in finalizer:
            fail(errors, f"final task report hook missing fragment: {fragment}")


def validate(quick: bool = False) -> int:
    root = repo_root()
    errors: list[str] = []
    validate_required_files(root, errors)
    validate_yaml_files(root, errors)
    validate_root_links(root, errors)
    validate_skills(root, errors)
    validate_json_toml(root, errors)
    validate_manifest_paths(root, errors)
    validate_hooks(root, errors)
    validate_delivery_templates(root, errors)
    validate_team_ready_governance(root, errors)
    validate_code_quality_profiles(root, errors)
    validate_prompt_catalog(root, errors)
    validate_seo_geo_assets(root, errors)
    validate_agent_adapter_strategy(root, errors)
    validate_native_adapters(root, errors)
    validate_delivery_artifact_generator(root, errors)
    validate_repository_intelligence(root, errors, quick)
    validate_secret_like_values(root, errors)
    validate_instruction_budgets(root, errors)
    validate_codex_rules_available(root, errors, quick)
    validate_governed_runtime(root, errors)

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("agent configuration validation passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quick", action="store_true", help="skip optional external CLI checks")
    args = parser.parse_args()
    return validate(quick=args.quick)


if __name__ == "__main__":
    raise SystemExit(main())
