import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {FacilityController,facilityView,directoryScope,directoryCursor,readDirectoryCursor} from '../apps/api/src/facilities';
import {facilitySearchSchema,provinces,normalizeDirectoryTerm} from '../packages/contracts/src/directory';
import type {FacilityBranch} from '../apps/api/src/domain';
import type {Database} from '../apps/api/src/database';
const now=new Date('2026-10-03T12:00:00Z');
function row(patch:Partial<FacilityBranch>={}):FacilityBranch{return {id:randomUUID(),legalName:'Bệnh viện A',branchName:'Cơ sở 1',address:'Hà Nội',areaCode:'01',officialUrl:'https://example.test',specialties:['Tim mạch'],services:[{specialtyId:'cardiology',evidence:{url:'https://example.test/branch',title:'Dịch vụ tại chi nhánh',checkedAt:'2026-10-01T00:00:00Z'},reviewDueAt:'2030-01-01T00:00:00Z'}],evidence:[{url:'https://example.test',title:'Official',checkedAt:'2026-10-01T00:00:00Z'}],status:'PUBLISHED',checkedAt:new Date('2026-10-01'),reviewDueAt:new Date('2030-01-01'),...patch};}
function database(rows:FacilityBranch[]){let reads=0;const make=(filters:((r:FacilityBranch)=>boolean)[]=[],after?:string)=>({where(field:keyof FacilityBranch,op:string,value:unknown){return make([...filters,r=>op==='array-contains'?(r[field] as unknown[]).includes(value):r[field]===value],after);},orderBy(){return this;},startAfter(name:unknown,id?:string){return make(filters,id??(name as {id:string}).id);},limit(limit:number){return {get:async()=>{const eligible=rows.filter(r=>filters.every(f=>f(r)));const index=after?eligible.findIndex(r=>r.id===after)+1:0;const page=eligible.slice(index,index+limit);reads+=page.length;return {size:page.length,docs:page.map(r=>({id:r.id,data:()=>r,get:(field:keyof FacilityBranch)=>r[field]}))};}};}});return {db:{collection:()=>make(),decode:async(_:string,r:FacilityBranch)=>r,get:async(_:string,id:string)=>rows.find(r=>r.id===id)??null} as unknown as Database,reads:()=>reads};}
describe('verified branch directory',()=>{
 it('keeps source freshness, publication and service freshness distinct',()=>{const branch=row();expect(facilityView(branch,now)?.services).toHaveLength(1);expect(facilityView({...branch,status:'DRAFT'},now)).toBeNull();expect(facilityView({...branch,reviewDueAt:now},now)).toBeNull();expect(facilityView({...branch,checkedAt:new Date('2030-01-01')},now)).toBeNull();expect(facilityView({...branch,services:[{...(branch.services![0] as object),reviewDueAt:now.toISOString()}]},now)?.services).toHaveLength(0);});
 it('does not accept invalid evidence or unsafe official URLs',()=>{expect(facilityView(row({officialUrl:'javascript:alert(1)'}),now)).toBeNull();expect(facilityView(row({evidence:[]}),now)).toBeNull();});
 it('binds continuation to query, filters, version and page size',()=>{const input=facilitySearchSchema.parse({query:'ha noi'}),scope=directoryScope(input);const token=directoryCursor(scope,'Tên',randomUUID());expect(readDirectoryCursor(token,scope).name).toBe('Tên');expect(()=>readDirectoryCursor(token,directoryScope({...input,areaCode:'01'}))).toThrow();expect(()=>readDirectoryCursor('bad!',scope)).toThrow();});
 it('intersects disease, verified services and province; never infers service from hospital name',async()=>{const wrong=row({areaCode:'79'}),unverified=row({services:[]}),match=row();const store=database([wrong,unverified,match]);const result=await new FacilityController(store.db).search({areaCode:'01',diseaseId:'heart-failure',query:'ha noi'});expect(result.items.map(b=>b.id)).toEqual([match.id]);expect(result.nextCursor).toBeNull();});
 it('continues across expired pages and never silently truncates at scan budget',async()=>{const expired=Array.from({length:256},()=>row({reviewDueAt:new Date('2020-01-01')})),last=row();const store=database([...expired,last]),controller=new FacilityController(store.db);const first=await controller.search({limit:1});expect(first.items).toEqual([]);expect(first.nextCursor).toBeTruthy();expect(store.reads()).toBe(256);const second=await controller.search({limit:1,cursor:first.nextCursor});expect(second.items[0]?.id).toBe(last.id);expect(second.nextCursor).toBeNull();});
 it('returns duplicate-free pages and hides an expired detail',async()=>{const rows=[row(),row(),row()],{db}=database(rows),controller=new FacilityController(db);const a=await controller.search({limit:1}),b=await controller.search({limit:1,cursor:a.nextCursor});expect(a.items[0]?.id).not.toBe(b.items[0]?.id);rows[0]!.reviewDueAt=new Date(0);await expect(controller.branch(rows[0]!.id)).rejects.toThrow();});
 it('has unique official two-digit codes and accent-insensitive normalization',()=>{expect(provinces).toHaveLength(34);expect(new Set(provinces.map(p=>p.code)).size).toBe(34);expect(provinces.every(p=>/^\d{2}$/.test(p.code))).toBe(true);expect(normalizeDirectoryTerm(' ĐẮK   LẮK ')).toBe('dak lak');});
});

describe('province migration boundaries',()=>{
 it('does not guess a former province or accept a pre-version code as current',async()=>{const {resolveProvinceAlias}=await import('../packages/contracts/src/directory');expect(resolveProvinceAlias('Thành phố Hà Nội')?.code).toBe('01');expect(resolveProvinceAlias('01','2024-01-01')).toBeNull();expect(resolveProvinceAlias('Hà Nam')).toBeNull();});
});
