'use client';
import Loading from './loading';
import {useEffect,useRef,useState} from 'react';
import Link from "./progress-link";
import dynamic from 'next/dynamic';
import {request,csrfHeaders,ApiError} from '@hs/api-client';
import type {ClassView,AssignmentView,LessonDocument,presentLesson,HeartBinding,LearningScenario} from '@hs/contracts';
import styles from './learning-workspace.module.css';
const Atlas=dynamic(()=>import('./full-body-anatomy'),{ssr:false,loading:()=> <Loading label="Đang mở mô hình"/>});
type Detail=ClassView&{assignments:AssignmentView[]};
type Assignment={id:string;content:ReturnType<typeof presentLesson>;lessonRevision:number;dueAt:string|null;submission:{reflection:string;createdAt:string}|null};
export default function ClassroomWorkspace({atlas}:{atlas?:{binding:HeartBinding;scenario:LearningScenario}}){
 const [activeAtlas,setActiveAtlas]=useState<string|null>(null);
 const [classes,setClasses]=useState<ClassView[]>([]),[active,setActive]=useState<Detail|null>(null),[assignment,setAssignment]=useState<Assignment|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[signedOut,setSignedOut]=useState(false);
 const [invite,setInvite]=useState<{token:string;expiresAt:string}|null>(null),[lessons,setLessons]=useState<LessonDocument[]>([]),[lessonCursor,setLessonCursor]=useState<string|null>(null),[reflection,setReflection]=useState('');
 const [results,setResults]=useState<{displayName:string;reflection:string;createdAt:string}[]|null>(null),[members,setMembers]=useState<{userId:string;displayName:string;revoked:boolean}[]|null>(null);
 const pending=useRef<AbortController|null>(null),keys=useRef(new Map<string,string>());
 async function run(work:(signal:AbortSignal)=>Promise<void>){pending.current?.abort();const c=new AbortController();pending.current=c;setBusy(true);setMessage('');try{await work(c.signal);}catch(e){if(!c.signal.aborted){setSignedOut(e instanceof ApiError&&e.status===401);setMessage(e instanceof ApiError&&e.status===401?'Đăng nhập để mở lớp học.':e instanceof ApiError&&e.status===404?'Lớp hoặc bài không khả dụng với tài khoản này.':e instanceof ApiError&&e.status===422?'Chưa hoàn tất: kiểm tra hạn nộp, nội dung bài và giới hạn lớp.':e instanceof ApiError&&e.status===409?'Bài đã thay đổi hoặc đã được nộp. Mở lại để xem bản mới nhất.':'Chưa hoàn tất thao tác. Bạn có thể thử lại.');}}finally{if(!c.signal.aborted)setBusy(false);}}
 async function read<T>(path:string,signal:AbortSignal):Promise<T>{const value=await request<T>(path,{signal});signal.throwIfAborted();return value;}
 async function write<T>(path:string,body:unknown,signal:AbortSignal,method='POST'):Promise<T>{const signature=JSON.stringify({path,body,method});if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());await request('/auth/csrf',{signal});signal.throwIfAborted();const value=await request<T>(path,{method,headers:{...csrfHeaders(),'Idempotency-Key':keys.current.get(signature)!},body:JSON.stringify(body),signal});signal.throwIfAborted();keys.current.delete(signature);return value;}
 function load(){void run(async signal=>{const data=await read<{items:ClassView[]}>('/api/v1/classes',signal);setClasses(data.items);setSignedOut(false);});}
 useEffect(()=>{load();const clear=()=>{pending.current?.abort();keys.current.clear();setActive(null);setActiveAtlas(null);setAssignment(null);setInvite(null);setLessons([]);setResults(null);setMembers(null);setReflection('');setClasses([]);load();};window.addEventListener('hs-auth-changed',clear);return()=>{pending.current?.abort();window.removeEventListener('hs-auth-changed',clear);};},[]);
 function open(id:string){setActiveAtlas(null);setAssignment(null);setReflection('');setResults(null);setMembers(null);setInvite(null);setLessons([]);void run(async signal=>{setActive(await read<Detail>(`/api/v1/classes/${id}`,signal));});}
 function openAssignment(id:string){if(!active)return;setActiveAtlas(null);setResults(null);setReflection('');void run(async signal=>{const row=await read<Assignment>(`/api/v1/classes/${active.id}/assignments/${id}`,signal);setAssignment(row);setReflection(row.submission?.reflection??'');});}
 async function lessonPage(signal:AbortSignal,cursor?:string){const page=await read<{items:LessonDocument[];nextCursor:string|null}>(`/api/v1/lessons?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,signal);setLessons(old=>cursor?[...old,...page.items]:page.items);setLessonCursor(page.nextCursor);}
 const unsent=!!assignment&&!assignment.submission&&reflection.length>0;
 return <><div className={styles.toolbar}><Link href="/giang-day">← Soạn bài</Link><button disabled={busy} onClick={load}>Làm mới</button></div><p role={busy?undefined:"status"}>{busy?<Loading inline label="Đang thực hiện yêu cầu"/>:message}</p>{signedOut&&<Link href="/tai-khoan">Đăng nhập</Link>}
 <div className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();const title=String(new FormData(e.currentTarget).get('title'));void run(async signal=>{const created=await write<ClassView>('/api/v1/classes',{title},signal);setClasses(old=>[...old,created]);setActive({...created,assignments:[]});setAssignment(null);setReflection('');setInvite(null);setResults(null);setMembers(null);setMessage('Đã tạo lớp.');});}}><h2>Tạo lớp</h2><label className={styles.field}>Tên lớp<input required name="title" maxLength={160}/></label><button disabled={busy||unsent}>Tạo lớp</button></form>
 <form className={styles.card} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),id=String(form.get('classId'));void run(async signal=>{await write(`/api/v1/classes/${encodeURIComponent(id)}/join`,{token:String(form.get('token')).trim(),displayName:String(form.get('displayName')).trim()},signal);const page=await read<{items:ClassView[]}>('/api/v1/classes',signal);setClasses(page.items);setMessage('Đã tham gia lớp.');});}}><h2>Tham gia lớp</h2><label className={styles.field}>Mã lớp<input name="classId" required maxLength={36}/></label><label className={styles.field}>Mã mời<input name="token" required maxLength={64} autoComplete="off"/></label><label className={styles.field}>Tên hiển thị trong lớp<input name="displayName" required maxLength={80}/></label><p className={styles.note}>Giảng viên xem được tên và bài nộp của bạn. Ghi chú cá nhân vẫn riêng tư.</p><button disabled={busy}>Tham gia</button></form></div>
 <div className={styles.toolbar}>{classes.map(c=><button key={c.id} disabled={busy||unsent} aria-pressed={active?.id===c.id} onClick={()=>open(c.id)}>{c.title}</button>)}</div>
 {active&&<section className={styles.editor}><h2>{active.title}</h2>{active.owner&&<><div className={styles.toolbar}><button disabled={busy} onClick={()=>void run(async signal=>{setInvite(await write(`/api/v1/classes/${active.id}/invites`,{},signal));})}>Tạo mã mời mới</button><button disabled={busy} onClick={()=>void run(signal=>lessonPage(signal))}>Chọn bài để giao</button><button disabled={busy} onClick={()=>void run(async signal=>setMembers((await read<{items:NonNullable<typeof members>}>(`/api/v1/classes/${active.id}/members`,signal)).items))}>Thành viên</button></div>{invite&&<div className={styles.block}><p>Mã cũ đã hết hiệu lực. Mã mới dùng trong 24 giờ; chỉ gửi cho người bạn muốn mời.</p><label className={styles.field}>Mã lớp<input readOnly value={active.id}/></label><label className={styles.field}>Mã mời<input readOnly value={invite.token}/></label></div>}
 {members&&<ul>{members.map(m=><li key={m.userId}>{m.displayName} {m.revoked?'· Đã thu hồi':<button disabled={busy} onClick={()=>void run(async signal=>{await write(`/api/v1/classes/${active.id}/members/${m.userId}`,{},signal,'DELETE');setMembers(old=>old?.map(v=>v.userId===m.userId?{...v,revoked:true}:v)??null);})}>Thu hồi quyền vào lớp</button>}</li>)}</ul>}
 {lessons.length>0&&<form className={styles.block} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),lesson=lessons.find(l=>l.id===form.get('lessonId'));if(!lesson)return;const deadline=String(form.get('dueAt'));void run(async signal=>{await write(`/api/v1/classes/${active.id}/assignments`,{lessonId:lesson.id,lessonRevision:lesson.revision,dueAt:deadline?new Date(deadline).toISOString():null},signal);setActive(await read<Detail>(`/api/v1/classes/${active.id}`,signal));setLessons([]);setMessage('Đã giao bài. Chỉnh sửa sau này không thay đổi bài học viên đã nhận.');});}}><label className={styles.field}>Bài đã lưu<select name="lessonId">{lessons.map(l=><option key={l.id} value={l.id}>{l.title} · v{l.revision}</option>)}</select></label><label className={styles.field}>Hạn nộp · giờ trên thiết bị<input name="dueAt" type="datetime-local"/></label><p className={styles.note}>Để trống nếu không có hạn. Học viên không thấy ghi chú của giảng viên.</p><button disabled={busy}>Giao bài</button>{lessonCursor&&<button type="button" disabled={busy} onClick={()=>void run(signal=>lessonPage(signal,lessonCursor))}>Thêm bài đã lưu</button>}</form>}</>}
 {!active.assignments.length&&<p>Lớp chưa có bài tập.</p>}{active.assignments.map(a=><div className={styles.toolbar} key={a.id}><button disabled={busy||unsent} onClick={()=>openAssignment(a.id)}>{a.title} · v{a.lessonRevision}</button>{active.owner&&<button disabled={busy} onClick={()=>void run(async signal=>setResults((await read<{items:NonNullable<typeof results>}>(`/api/v1/classes/${active.id}/results/${a.id}`,signal)).items))}>Xem bài nộp</button>}</div>)}
 {results&&<section><h3>{results.length} bài nộp</h3>{results.map((r,i)=><article className={styles.block} key={i}><strong>{r.displayName}</strong><p>{r.reflection||'Đã xác nhận hoàn thành bài.'}</p><time dateTime={r.createdAt}>{new Date(r.createdAt).toLocaleString('vi-VN')}</time></article>)}</section>}
 {assignment&&<section className={styles.editor}><h2>{assignment.content.title}</h2><p>Bản được giao · v{assignment.lessonRevision}{assignment.dueAt?` · Hạn ${new Date(assignment.dueAt).toLocaleString('vi-VN')}`:' · Không có hạn nộp'}</p><ul>{assignment.content.objectives.map((o,i)=><li key={i}>{o}</li>)}</ul>{assignment.content.blocks.map(b=><article className={styles.block} key={b.id}><h3>{b.title}</h3>{b.kind==='text'?<p>{b.text}</p>:b.kind==='topic'?<Link href={`/hoc-tap/sinh-ly-benh?topic=${b.topicId}`}>Xem bài học và tài liệu</Link>:b.kind==='quiz'?<Link href={`/hoc-tap?quiz=${b.quizId}&revision=${b.quizRevision}`}>Làm bài kiểm tra</Link>:atlas?<><button aria-expanded={activeAtlas===b.id} onClick={()=>setActiveAtlas(activeAtlas===b.id?null:b.id)}>{activeAtlas===b.id?'Đóng mô hình':'Mở góc nhìn 3D'}</button>{activeAtlas===b.id&&<Atlas key={b.id} embedded initialScene={b.snapshot.scene} {...atlas}/>}</>:<p>Mô hình chưa khả dụng trong bản này.</p>}</article>)}{!active.owner&&<form onSubmit={e=>{e.preventDefault();void run(async signal=>{const response=await write<{createdAt:string}>(`/api/v1/classes/${active.id}/assignments/${assignment.id}/submissions`,{reflection},signal);setAssignment({...assignment,submission:{reflection,createdAt:response.createdAt}});setMessage('Đã ghi nhận hoàn thành bài.');});}}><label className={styles.field}>Điều bạn học được · không bắt buộc<textarea disabled={busy||!!assignment.submission} value={reflection} maxLength={2000} onChange={e=>setReflection(e.target.value)}/></label><p className={styles.note}>{unsent&&<button type="button" onClick={()=>setReflection('')}>Bỏ phản hồi chưa nộp</button>}Giảng viên sẽ đọc phản hồi này. Không ghi thông tin người bệnh. Hoàn thành bài không thay cho điểm kiểm tra hoặc chứng nhận năng lực.</p><button disabled={busy||!!assignment.submission}>{assignment.submission?'Đã nộp':'Xác nhận đã học xong'}</button></form>}</section>}
 </section>}</>;
}
