'use client';
import {useEffect,useRef,useState} from 'react';
import {ApiError,request,csrfHeaders} from '@hs/api-client';
import styles from './learning-workspace.module.css';
type Note={id:string;text:string;anatomyId:string|null;revision:number};
export default function PersonalStudy(){
 const [notes,setNotes]=useState<Note[]>([]),[next,setNext]=useState<string|null>(null),[selected,setSelected]=useState<Note|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>{const clear=()=>{pending.current?.abort();setNotes([]);setNext(null);setSelected(null);setText('');setMessage('');setBusy(false);setLoaded(false);};window.addEventListener('hs-auth-changed',clear);return()=>{clear();window.removeEventListener('hs-auth-changed',clear);};},[]);
 async function load(cursor?:string){pending.current?.abort();const c=new AbortController();pending.current=c;setBusy(true);try{const page=await request<{items:Note[];nextCursor:string|null}>(`/api/v1/notes?limit=20${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`,{signal:c.signal});if(c.signal.aborted)return;setNotes(old=>cursor?[...old,...page.items]:page.items);setNext(page.nextCursor);setLoaded(true);setMessage('');}catch(e){if(!c.signal.aborted)setMessage(e instanceof ApiError&&e.status===401?'Đăng nhập để xem ghi chú riêng tư.':'Chưa tải được ghi chú. Bạn có thể thử lại.');}finally{if(!c.signal.aborted)setBusy(false);}}
 async function save(){if(!selected)return;pending.current?.abort();const c=new AbortController();pending.current=c;setBusy(true);try{await request('/auth/csrf',{signal:c.signal});const row=await request<Note>(`/api/v1/notes/${selected.id}`,{method:'PATCH',headers:{...csrfHeaders(),'If-Match':`"${selected.revision}"`},body:JSON.stringify({text,anatomyId:selected.anatomyId}),signal:c.signal});if(c.signal.aborted)return;setNotes(old=>old.map(n=>n.id===row.id?row:n));setSelected(row);setText(row.text);setMessage('Đã lưu ghi chú.');}catch(e){if(!c.signal.aborted)setMessage(e instanceof ApiError&&e.status===409?'Ghi chú đã thay đổi ở nơi khác. Nội dung đang sửa vẫn được giữ.':'Chưa lưu được ghi chú. Nội dung đang sửa vẫn được giữ.');}finally{if(!c.signal.aborted)setBusy(false);}}
 const dirty=!!selected&&text!==selected.text;
 return <section className={styles.editor} aria-label="Ghi chú học tập"><h2>Ghi chú của bạn</h2><p className={styles.note}>Ghi chú riêng khi học giải phẫu, không chia sẻ với lớp.</p><button disabled={busy||dirty} onClick={()=>void load()}>Mở ghi chú</button><p role="status">{busy?'Đang xử lý…':message}</p>{loaded&&!notes.length&&<p>Chưa có ghi chú. Bạn có thể thêm khi khám phá giải phẫu.</p>}<div className={styles.toolbar}>{notes.map(n=><button disabled={busy||dirty} key={n.id} onClick={()=>{setSelected(n);setText(n.text);}}>{n.text.slice(0,70)}{n.text.length>70?'…':''}</button>)}</div>{next&&<button disabled={busy||dirty} onClick={()=>void load(next)}>Xem thêm ghi chú</button>}{selected&&<form onSubmit={e=>{e.preventDefault();void save();}}><label className={styles.field}>Nội dung ghi chú<textarea required disabled={busy} maxLength={5000} value={text} onChange={e=>setText(e.target.value)}/></label><div className={styles.toolbar}><button disabled={busy||!dirty||!text.trim()}>Lưu ghi chú</button><button disabled={busy} type="button" onClick={()=>{setSelected(null);setText('');}}>Đóng và bỏ thay đổi chưa lưu</button></div></form>}</section>;
}
