'use client';
import dynamic from 'next/dynamic';
import {initialBodyScene} from '@hs/anatomy-viewer/scene-history';
import type {HeartBinding,LearningScenario} from '@hs/contracts';
import {bodySnapshot} from '@hs/contracts';
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { Plus,Save,ArrowUp,ArrowDown,Trash2,Presentation,ArrowLeft,ChevronLeft,ChevronRight,Printer } from 'lucide-react';
import { request,csrfHeaders,ApiError } from '@hs/api-client';
import { learningPositionSchema,lessonContentSchema,presentLesson,type LessonDocument,type LessonBlock } from '@hs/contracts';
import styles from './learning-workspace.module.css';
const Atlas=dynamic(()=>import('./full-body-anatomy'),{ssr:false});
type Topic={id:string;title:string};
export default function TeachingWorkspace({topics,atlas}:{topics:Topic[];atlas?:{binding:HeartBinding;scenario:LearningScenario}}){
 const [quizOptions,setQuizOptions]=useState<{id:string;title:string;revision:number}[]>([]);
 const [editingAtlas,setEditingAtlas]=useState<string|null>(null);
 const [lessons,setLessons]=useState<Pick<LessonDocument,'id'|'title'|'revision'>[]>([]),[lesson,setLesson]=useState<LessonDocument|null>(null),[cursor,setCursor]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[signedOut,setSignedOut]=useState(false),[dirty,setDirty]=useState(false),[loaded,setLoaded]=useState(false);
 const [presentation,setPresentation]=useState<ReturnType<typeof presentLesson>|null>(null),[slide,setSlide]=useState(0);
 const createKey=useRef<string|null>(null),saveKey=useRef<{body:string;key:string}|null>(null);
 const pending=useRef<AbortController|null>(null);const baseline=useRef<LessonDocument|null>(null);
 function controller(){pending.current?.abort();const value=new AbortController();pending.current=value;return value;}
 function error(e:unknown){setSignedOut(e instanceof ApiError&&e.status===401);setMessage(e instanceof ApiError&&e.status===409?'Bài đã thay đổi ở nơi khác. Bản bạn đang sửa vẫn được giữ; sao chép nội dung trước khi mở lại bài.':e instanceof ApiError&&e.status===401?'Đăng nhập để mở và lưu bài giảng riêng tư.':'Chưa hoàn tất thao tác. Nội dung đang sửa vẫn được giữ; bạn có thể thử lại.');}
 async function list(after?:string){const c=controller();setBusy(true);try{const page=await request<{items:LessonDocument[];nextCursor:string|null}>(`/api/v1/lessons?limit=20${after?`&cursor=${encodeURIComponent(after)}`:''}`,{signal:c.signal});if(c.signal.aborted)return;setLessons(old=>after?[...old,...page.items]:page.items);setCursor(page.nextCursor);setLoaded(true);setSignedOut(false);setMessage('');}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 useEffect(()=>{void list();const clear=()=>{pending.current?.abort();createKey.current=null;saveKey.current=null;setLesson(null);setQuizOptions([]);setEditingAtlas(null);baseline.current=null;setPresentation(null);setDirty(false);setLessons([]);setCursor(null);setBusy(false);void list();};window.addEventListener('hs-auth-changed',clear);return()=>{pending.current?.abort();window.removeEventListener('hs-auth-changed',clear);};},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function edit(patch:Partial<LessonDocument>){if(!lesson)return;setLesson({...lesson,...patch});setDirty(true);setMessage('');}
 async function loadQuizzes(){const c=controller();setBusy(true);try{const page=await request<{items:typeof quizOptions}>('/api/v1/quizzes',{signal:c.signal});if(c.signal.aborted)return;setQuizOptions(page.items);if(!page.items.length)setMessage('Chưa có bài kiểm tra đã xuất bản để thêm.');}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 async function create(){if(dirty)return;createKey.current??=crypto.randomUUID();const c=controller();setBusy(true);try{await request('/auth/csrf',{signal:c.signal});const row=await request<LessonDocument>('/api/v1/lessons',{method:'POST',headers:{...csrfHeaders(),'Idempotency-Key':createKey.current},signal:c.signal,body:JSON.stringify({title:'Bài giảng mới',description:''})});if(c.signal.aborted)return;createKey.current=null;setLessons(old=>[row,...old]);setLesson(row);baseline.current=row;setDirty(false);setPresentation(null);setMessage('Đã tạo bài giảng.');}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 async function open(id:string){if(dirty)return;const c=controller();setBusy(true);try{const row=await request<LessonDocument>(`/api/v1/lessons/${id}`,{signal:c.signal});if(c.signal.aborted)return;setLesson(row);baseline.current=row;setPresentation(null);setDirty(false);setMessage('');}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 async function save(){if(!lesson)return;const parsed=lessonContentSchema.safeParse({title:lesson.title,description:lesson.description,objectives:lesson.objectives.filter(o=>o.trim()),blocks:lesson.blocks});if(!parsed.success){setMessage('Điền tiêu đề và nội dung cho từng phần; tối đa 100 phần và 10 mục tiêu.');return;}const body=JSON.stringify({id:lesson.id,revision:lesson.revision,input:parsed.data});if(saveKey.current?.body!==body)saveKey.current={body,key:crypto.randomUUID()};const c=controller();setBusy(true);try{await request('/auth/csrf',{signal:c.signal});const saved=await request<LessonDocument>(`/api/v1/lessons/${lesson.id}`,{method:'PATCH',headers:{...csrfHeaders(),'Idempotency-Key':saveKey.current.key,'If-Match':`"${lesson.revision}"`},signal:c.signal,body:JSON.stringify(parsed.data)});if(c.signal.aborted)return;setLesson(saved);baseline.current=saved;setLessons(old=>old.map(row=>row.id===saved.id?saved:row));setDirty(false);setMessage('Đã lưu bài giảng.');}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 async function present(){if(!lesson||dirty)return;const c=controller();setBusy(true);try{const value=await request<ReturnType<typeof presentLesson>>(`/api/v1/lessons/${lesson.id}/presentation`,{signal:c.signal});if(c.signal.aborted)return;setSlide(0);setPresentation(value);}catch(e){if(!c.signal.aborted)error(e);}finally{if(!c.signal.aborted)setBusy(false);}}
 function blockEdit(id:string,patch:Partial<LessonBlock>){if(!lesson)return;edit({blocks:lesson.blocks.map(b=>b.id===id?{...b,...patch} as LessonBlock:b)});}
 function move(index:number,delta:number){if(!lesson)return;const blocks=[...lesson.blocks];const other=index+delta;if(other<0||other>=blocks.length)return;[blocks[index],blocks[other]]=[blocks[other]!,blocks[index]!];edit({blocks});}
 const presenterHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(presentation)presenterHeading.current?.focus();},[presentation]);
 const current=presentation?.blocks[slide];
 if(presentation)return <section className={styles.presentation} aria-label="Trình chiếu bài giảng"><div className={styles.toolbar}><button onClick={()=>setPresentation(null)}><ArrowLeft size={16}/>Về soạn bài</button><button title="In bài giảng" aria-label="In bài giảng" onClick={()=>window.print()}><Printer size={18}/></button></div><h2 ref={presenterHeading} tabIndex={-1}>{presentation.title}</h2><p>{presentation.description}</p><ul>{presentation.objectives.map((o,i)=><li key={i}>{o}</li>)}</ul><div className={`${styles.present} ${styles.screenOnly}`}>{current?<><h3>{current.title}</h3>{current.kind==='text'?<p>{current.text}</p>:current.kind==='atlas'?(atlas?<Atlas key={current.id} embedded initialScene={current.snapshot.scene} {...atlas}/>:<p>Chưa có mô hình cho bài này.</p>):current.kind==='topic'?<Link href={`/hoc-tap/sinh-ly-benh?topic=${encodeURIComponent(current.topicId)}`}>Xem bài học →</Link>:<Link href={`/hoc-tap?quiz=${current.quizId}&revision=${current.quizRevision}`}>Mở bài kiểm tra →</Link>}</>:<p>Bài giảng chưa có nội dung.</p>}</div><div className={styles.printOnly}>{presentation.blocks.map((block,i)=><section key={block.id}><h3>{i+1}. {block.title}</h3>{block.kind==='text'?<p>{block.text}</p>:block.kind==='topic'?<a href={`/hoc-tap/sinh-ly-benh?topic=${block.topicId}`}>Bài học và tài liệu tham khảo</a>:block.kind==='quiz'?<a href={`/hoc-tap?quiz=${block.quizId}&revision=${block.quizRevision}`}>Bài kiểm tra · phiên bản {block.quizRevision}</a>:<p>Góc nhìn giải phẫu. Mở bài giảng để xem mô hình 3D.</p>}</section>)}</div><div className={styles.actions}><button aria-label="Phần trước" title="Phần trước" disabled={slide===0} onClick={()=>setSlide(n=>n-1)}><ChevronLeft size={18}/></button><span role="status">{presentation.blocks.length?slide+1:0} / {presentation.blocks.length}</span><button aria-label="Phần sau" title="Phần sau" disabled={slide>=presentation.blocks.length-1} onClick={()=>setSlide(n=>n+1)}><ChevronRight size={18}/></button></div></section>;
 return <><p role="status">{busy?'Đang xử lý…':message}</p>{signedOut?<Link href="/tai-khoan">Đăng nhập</Link>:<div className={styles.toolbar}><button disabled={busy||dirty} onClick={()=>void create()}><Plus size={16}/>Bài giảng</button><button disabled={busy||dirty} onClick={()=>void list()}>Làm mới</button></div>}
 {dirty&&<p className={styles.note}>Bạn có thay đổi chưa lưu. Lưu bài trước khi chuyển, hoặc bỏ thay đổi. <button disabled={busy} onClick={()=>{setLesson(baseline.current);setDirty(false);setMessage('Đã bỏ thay đổi chưa lưu.');}}>Bỏ thay đổi</button></p>}
 <div className={styles.workspace}><aside className={styles.list} aria-label="Bài giảng của bạn">{lessons.map(row=><button key={row.id} aria-current={row.id===lesson?.id?'true':undefined} disabled={busy||dirty} onClick={()=>void open(row.id)}>{row.title}</button>)}{loaded&&!lessons.length&&<p>Chưa có bài giảng. Chọn “Bài giảng” để tạo bài mới.</p>}{cursor&&<button disabled={busy||dirty} onClick={()=>void list(cursor)}>Xem thêm bài</button>}</aside>
 {lesson&&<section className={styles.editor} aria-label="Soạn bài giảng"><label className={styles.field}>Tiêu đề<input disabled={busy} value={lesson.title} maxLength={160} onChange={e=>edit({title:e.target.value})}/></label><label className={styles.field}>Giới thiệu<textarea disabled={busy} value={lesson.description} maxLength={2000} onChange={e=>edit({description:e.target.value})}/></label><label className={styles.field}>Mục tiêu học tập · mỗi dòng một mục<textarea disabled={busy} value={lesson.objectives.join('\n')} maxLength={3010} onChange={e=>edit({objectives:e.target.value.split('\n')})}/></label>
 {lesson.blocks.map((block,index)=><section className={styles.block} key={block.id}><header><strong>Phần {index+1}</strong><div className={styles.actions}><button title="Đưa lên" aria-label={`Đưa phần ${index+1} lên`} disabled={busy||index===0} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button title="Đưa xuống" aria-label={`Đưa phần ${index+1} xuống`} disabled={busy||index===lesson.blocks.length-1} onClick={()=>move(index,1)}><ArrowDown size={16}/></button><button title="Bỏ phần" aria-label={`Bỏ phần ${index+1}`} disabled={busy} onClick={()=>edit({blocks:lesson.blocks.filter(b=>b.id!==block.id)})}><Trash2 size={16}/></button></div></header><label className={styles.field}>Tên phần<input disabled={busy} value={block.title} maxLength={160} onChange={e=>blockEdit(block.id,{title:e.target.value})}/></label>{block.kind==='text'&&<label className={styles.field}>Nội dung<textarea disabled={busy} value={block.text} maxLength={5000} onChange={e=>blockEdit(block.id,{text:e.target.value})}/></label>}{block.kind==='quiz'&&<p>Bài kiểm tra đã xuất bản · v{block.quizRevision}. Người học cần đăng nhập để lưu kết quả.</p>}{block.kind==='atlas'&&<><button disabled={busy||!atlas} onClick={()=>setEditingAtlas(editingAtlas===block.id?null:block.id)}>Chỉnh góc nhìn 3D</button>{editingAtlas===block.id&&atlas&&<Atlas key={block.id} embedded initialScene={block.snapshot.scene} {...atlas} onCapture={scene=>{blockEdit(block.id,{snapshot:bodySnapshot(scene)});setEditingAtlas(null);}}/>}</>}{block.kind==='topic'&&<label className={styles.field}>Chủ đề<select disabled={busy} value={block.topicId} onChange={e=>blockEdit(block.id,{topicId:learningPositionSchema.shape.topicId.parse(e.target.value)})}>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>}<details><summary>Ghi chú người dạy · không trình chiếu</summary><label className={styles.field}>Ghi chú riêng<textarea disabled={busy} maxLength={2000} value={block.speakerNotes} onChange={e=>blockEdit(block.id,{speakerNotes:e.target.value})}/></label></details></section>)}
 <div className={styles.toolbar}><button disabled={busy||lesson.blocks.length>=100} onClick={()=>edit({blocks:[...lesson.blocks,{id:crypto.randomUUID(),kind:'text',title:'Nội dung mới',text:'',speakerNotes:''}]})}><Plus size={16}/>Nội dung</button>{topics[0]&&<button disabled={busy||lesson.blocks.length>=100} onClick={()=>edit({blocks:[...lesson.blocks,{id:crypto.randomUUID(),kind:'topic',title:topics[0]!.title,topicId:learningPositionSchema.shape.topicId.parse(topics[0]!.id),speakerNotes:''}]})}><Plus size={16}/>Chủ đề bệnh</button>}{atlas&&<button disabled={busy||lesson.blocks.length>=100} onClick={()=>edit({blocks:[...lesson.blocks,{id:crypto.randomUUID(),kind:'atlas',title:'Góc nhìn giải phẫu',snapshot:bodySnapshot(initialBodyScene()),speakerNotes:''}]})}><Plus size={16}/>Góc nhìn 3D</button>}<button disabled={busy||lesson.blocks.length>=100} onClick={()=>void loadQuizzes()}>Thêm bài kiểm tra</button><button disabled={busy||!dirty} onClick={()=>void save()}><Save size={16}/>Lưu</button><button disabled={busy||dirty} onClick={()=>void present()}><Presentation size={16}/>Trình chiếu</button></div>{quizOptions.length>0&&<section className={styles.list} aria-label="Chọn bài kiểm tra">{quizOptions.map(q=><button key={q.id} disabled={busy||lesson.blocks.length>=100} onClick={()=>{edit({blocks:[...lesson.blocks,{id:crypto.randomUUID(),kind:'quiz',title:q.title,quizId:q.id,quizRevision:q.revision,speakerNotes:''}]});setQuizOptions([]);}}>{q.title} · v{q.revision}</button>)}</section>}</section>}
 </div></>;
}
