'use client';
import { useEffect, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, Check, CreditCard, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { ApiError } from '@hs/api-client';
import type { AccountSettings } from '@hs/contracts';
import { accountName, initials, studyRoles } from '../../lib/account';
import { useAccount } from './account-shell';
import RevokeSessions from './account-security';
import AccountExport from './account-export';

function Heading({ title, children }: { title: string; children: ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">KHÔNG GIAN CỦA BẠN</div><h1>{title}</h1><p>{children}</p></div></div>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="panel"><div className="panel-head"><h2>{title}</h2></div><div className="panel-body">{children}</div></section>; }
function AccountForm({ preferences = false }: { preferences?: boolean }) {
  const { account, save, setDirty } = useAccount();
  const [draft, setDraft] = useState<AccountSettings>({ displayName: account.displayName, studyRole: account.studyRole, timezone: account.timezone, reducedMotion: account.reducedMotion });
  const [revision, setRevision] = useState(account.revision);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const changed = draft.displayName !== account.displayName || draft.studyRole !== account.studyRole || draft.timezone !== account.timezone || draft.reducedMotion !== account.reducedMotion;
  useEffect(() => { setDirty(changed); return () => setDirty(false); }, [changed, setDirty]);
  function change(value: Partial<AccountSettings>) { setDraft(current => ({ ...current, ...value })); setMessage(''); }
  return <form className="panel" onSubmit={event => { event.preventDefault(); if (busy) return; setBusy(true); setMessage(''); void save(draft, revision).then(() => { setDraft(current => ({ ...current, displayName: current.displayName.trim() })); setRevision(revision + 1); setMessage('Đã lưu thay đổi.'); }).catch(error => setMessage(error instanceof ApiError && error.status === 409 ? 'Thông tin đã được cập nhật ở nơi khác. Tải lại trang để xem bản mới trước khi chỉnh sửa tiếp.' : 'Chưa xác nhận được việc lưu. Nội dung bạn nhập vẫn ở đây; hãy thử lại.')).finally(() => setBusy(false)); }}>
    <div className="panel-head"><h2>{preferences ? 'Trải nghiệm tài khoản' : 'Thông tin cá nhân'}</h2><p>{preferences ? 'Áp dụng cho khu vực quản lý tài khoản của bạn.' : 'Tên hiển thị chỉ thay đổi trong HumanScope, không đổi tài khoản Google.'}</p></div>
    <div className="panel-body"><fieldset disabled={busy} style={{ border: 0, padding: 0, margin: 0 }}><div className="form-grid">
      {!preferences && <><div className="field"><label htmlFor="display-name">Tên hiển thị</label><input id="display-name" autoComplete="name" maxLength={80} required value={draft.displayName} onChange={event => change({ displayName: event.target.value })} /></div><div className="field"><label htmlFor="study-role">Bạn đang học với vai trò nào?</label><select id="study-role" value={draft.studyRole} onChange={event => change({ studyRole: event.target.value as AccountSettings['studyRole'] })}>{Object.entries(studyRoles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><small>Không bắt buộc chia sẻ vai trò của bạn.</small></div><div className="field span-all"><label htmlFor="account-email">Email đăng nhập</label><input id="account-email" readOnly value={account.email ?? 'Chưa có email'} /><small>Email do nhà cung cấp đăng nhập quản lý.</small></div></>}
      {preferences && <><div className="field span-all"><label htmlFor="timezone">Múi giờ hiển thị hoạt động</label><select id="timezone" value={draft.timezone} onChange={event => change({ timezone: event.target.value })}>{[...new Set([account.timezone, 'Asia/Ho_Chi_Minh', 'Asia/Bangkok', 'Asia/Tokyo', 'America/Chicago', 'America/New_York', 'Europe/London', 'UTC'])].map(zone => <option key={zone}>{zone}</option>)}</select></div><label className="toggle-label span-all"><span><span className="label-title">Giảm chuyển động</span><span className="label-note">Hạn chế hiệu ứng chuyển động trong các trang tài khoản.</span></span><input type="checkbox" className="switch" checked={draft.reducedMotion} onChange={event => change({ reducedMotion: event.target.checked })} /></label>{!draft.displayName.trim() && <p className="span-all">Hãy <Link href="/tai-khoan/ho-so" className="text-link">đặt tên hiển thị</Link> trước khi lưu tùy chọn.</p>}</>}
    </div></fieldset><p className="account-message" role="status" aria-live="polite">{message}</p></div><div className="form-footer"><button type="button" disabled={busy || !changed} onClick={() => { setDraft({ displayName: account.displayName, studyRole: account.studyRole, timezone: account.timezone, reducedMotion: account.reducedMotion }); setRevision(account.revision); setMessage(''); }}>Bỏ thay đổi</button><button className="primary" disabled={busy || !changed || !draft.displayName.trim()}>{busy ? 'Đang lưu…' : 'Lưu thay đổi'}</button></div>
  </form>;
}
function Plans() { return <><Heading title="Gói của bạn">Tiếp tục khám phá miễn phí. Nâng cấp khi bạn cần nhiều hơn.</Heading><div className="price-layout"><section className="price-card"><span className="badge blue">Gói hiện tại</span><h2>HumanScope Free</h2><div className="price">0 <span>USD</span></div><p>Không gian để bắt đầu tìm hiểu cơ thể người.</p><ul><li><Check />Khám phá các mô hình giải phẫu công khai</li><li><Check />Tìm hiểu nội dung trong thư viện</li><li><Check />Lưu ghi chú với tài khoản cá nhân</li></ul><Link className="button" href="/">Tiếp tục khám phá</Link></section><section className="price-card featured"><span className="badge">Chưa mở bán</span><h2>HumanScope Pro</h2><div className="price">19.99 <span>USD / năm</span></div><p>Một gói năm cho trải nghiệm học chuyên sâu hơn.</p><ul><li><Sparkles />Quyền lợi Pro đang được hoàn thiện</li><li><Check />Chỉ có gói thanh toán theo năm</li><li><LockKeyhole />Chưa phát sinh giao dịch tại đây</li></ul><button disabled>Nâng cấp chưa khả dụng</button><p className="small-text">Giá dự kiến. Quyền lợi và điều kiện thanh toán sẽ được hiển thị trước khi bạn mua.</p></section></div></>; }
export default function AccountPage({ section }: { section: string }) {
  const { account } = useAccount();
  const date = (value: string) => new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short', timeZone: account.timezone }).format(new Date(value));
  if (section === 'ho-so') return <><Heading title="Hồ sơ cá nhân">Một vài thông tin để không gian này gần với bạn hơn.</Heading><AccountForm key="profile" /></>;
  if (section === 'tuy-chon') return <><Heading title="Tùy chọn">Điều chỉnh cách bạn sử dụng không gian tài khoản.</Heading><AccountForm key="preferences" preferences /></>;
  if (['goi', 'nang-cap'].includes(section)) return <Plans />;
  if (section === 'bao-mat') return <><Heading title="Đăng nhập & bảo mật">Kiểm tra cách đăng nhập và những phiên còn hiệu lực.</Heading><Panel title="Phương thức đăng nhập"><div className="row"><div><h3>{account.googleLinked ? 'Tài khoản Google' : 'Tài khoản đã xác thực'}</h3><p>{account.email ?? 'Chưa có email'}</p></div><span className="badge green">Đã kết nối</span></div><p className="inline-message">Mật khẩu và xác minh hai bước được quản lý tại nhà cung cấp đăng nhập.</p></Panel><Panel title="Phiên đăng nhập"><p className="small-text">Hoạt động gần nhất theo múi giờ {account.timezone}. Phiên không hoạt động quá 30 phút sẽ hết hiệu lực.</p>{account.sessionsTruncated && <p className="notice warning">Danh sách chỉ hiển thị một phần các phiên.</p>}<ul className="session-list">{account.sessions.map((session, index) => <li key={`${session.lastSeenAt}-${index}`}><strong>{session.current ? 'Phiên bạn đang sử dụng' : 'Phiên đăng nhập khác'}</strong><p>Hoạt động: {date(session.lastSeenAt)}</p><p>Hết hạn tối đa: {date(session.expiresAt)}</p></li>)}</ul>{!account.sessions.length && <p>Chưa có thông tin phiên để hiển thị. Tải lại trang để kiểm tra.</p>}<p className="inline-message">Dùng nút Đăng xuất trong menu tài khoản để kết thúc phiên hiện tại.</p><RevokeSessions /></Panel></>;
  if (section === 'thanh-toan' || section === 'ket-qua') return <><Heading title="Thanh toán">Thông tin thanh toán của gói HumanScope.</Heading><section className="panel empty"><span className="icon-box"><CreditCard /></span><h2>Thanh toán chưa mở</h2><p>HumanScope Pro chưa mở bán. Hiện chưa có dữ liệu hóa đơn hoặc phương thức thanh toán để hiển thị.</p><Link href="/tai-khoan/goi" className="button">Xem các gói</Link></section></>;
  if (section === 'du-lieu' || section === 'xoa') return <><Heading title="Dữ liệu & quyền riêng tư">Hiểu và quản lý thông tin gắn với tài khoản của bạn.</Heading><Panel title="Thông tin của bạn"><div className="row"><div><h3>Hồ sơ cá nhân</h3><p>Tên hiển thị, vai trò học tập và tùy chọn tài khoản.</p></div><Link className="text-link" href="/tai-khoan/ho-so">Chỉnh sửa</Link></div><div className="row"><div><h3>Ghi chú và học tập</h3><p>Mở không gian học tập để xem nội dung của bạn.</p></div><Link className="text-link" href="/hoc-tap">Mở học tập</Link></div></Panel><Panel title="Tải xuống dữ liệu"><AccountExport /></Panel><Panel title="Xóa tài khoản"><p>Chưa hỗ trợ xóa tài khoản từ giao diện này. Đăng xuất chỉ kết thúc phiên, không xóa thông tin đã lưu.</p><div className="footer-actions"><button disabled>Xóa tài khoản chưa khả dụng</button></div></Panel></>;
  if (section === 'tro-giup') return <><Heading title="Trợ giúp">Những điều cần biết khi sử dụng tài khoản HumanScope.</Heading><Panel title="Câu hỏi thường gặp">{[['Tôi có cần mua Pro để bắt đầu?', 'Bạn có thể khám phá nội dung công khai miễn phí. Đăng nhập để sử dụng các chức năng cá nhân hiện có.'], ['Pro có giá bao nhiêu?', 'Giá dự kiến là 19.99 USD mỗi năm, chỉ có gói năm. Pro hiện chưa mở bán.'], ['Vì sao tôi cần đăng nhập lại?', 'Phiên hết hiệu lực khi không hoạt động quá 30 phút hoặc đến thời hạn tối đa. Đăng nhập lại bằng tài khoản cũ để tiếp tục.'], ['Tôi có thể đổi email tại đây không?', 'Email đăng nhập do nhà cung cấp xác thực quản lý. Bạn có thể đổi tên hiển thị riêng trong hồ sơ HumanScope.']].map(([question, answer]) => <details className="plain-details" key={question}><summary>{question}</summary><p>{answer}</p></details>)}</Panel><Link className="text-link" href="/gioi-thieu">Tìm hiểu về HumanScope <ArrowRight size={14} /></Link></>;
  return <><Heading title="Tài khoản của bạn">Thông tin cá nhân, gói sử dụng và những tùy chọn quan trọng.</Heading><section className="identity-banner"><div className="identity-person"><span className="avatar large">{initials(account.displayName)}</span><div><h2>{accountName(account)}</h2><p>{account.email ?? 'Chưa có email'}</p><div className="identity-detail"><span>{account.studyRole === 'unspecified' ? 'Tài khoản cá nhân' : studyRoles[account.studyRole]}</span><span className="badge blue">Free</span></div></div></div><Link className="button" href="/tai-khoan/ho-so">Chỉnh sửa hồ sơ <ArrowRight /></Link></section><div className="overview-columns"><section className="membership"><div className="membership-top"><span className="membership-label">GÓI CỦA BẠN</span><Sparkles /></div><h2>Không ngừng khám phá.</h2><p>Bạn đang sử dụng HumanScope Free. Tiếp tục tìm hiểu cơ thể người theo nhịp học của mình.</p><div className="membership-detail"><strong>HumanScope Free</strong><span>Miễn phí</span></div><Link className="button membership-button" href="/tai-khoan/goi">Khám phá các gói <ArrowRight /></Link></section><section className="account-health"><div className="section-title"><h2>Đăng nhập & bảo mật</h2><ShieldCheck /></div><div className="rule" /><h3>{account.googleLinked ? 'Đăng nhập bằng Google' : 'Phiên đã xác thực'}</h3><p>{account.email ?? 'Tài khoản của bạn'}</p><div className="rule" /><p className="small-text">Kiểm tra các phiên đang hoạt động và cách bảo vệ tài khoản của bạn.</p><Link className="text-link" href="/tai-khoan/bao-mat">Quản lý đăng nhập <ArrowRight size={14} /></Link></section></div><div className="section-heading"><h2>Theo cách của bạn</h2></div><div className="settings-links"><Link href="/tai-khoan/tuy-chon"><span className="settings-symbol"><BookOpen /></span><div><h3>Tùy chọn trải nghiệm</h3><p>Múi giờ và chuyển động</p></div><ArrowRight /></Link><Link href="/tai-khoan/du-lieu"><span className="settings-symbol"><LockKeyhole /></span><div><h3>Dữ liệu & quyền riêng tư</h3><p>Thông tin gắn với tài khoản</p></div><ArrowRight /></Link></div><div className="account-footer"><span>HumanScope · Không gian học tập cá nhân</span><Link href="/tai-khoan/tro-giup">Bạn cần trợ giúp?</Link></div></>;
}
