import "server-only";
import type { QuizQuestion } from "./learning-quiz";
import { coronaryScenarios } from "./coronary-scenarios";

type Extra = [id: string, kind: string, question: string, options: [string, string, string], correct: number, explanation: string, stageId: string];
const extras: Record<keyof typeof coronaryScenarios, Extra[]> = {
  infarction: [
    ["trigger", "Cơ chế bệnh sinh", "Trong cơ chế nhồi máu cơ tim đang mô phỏng, biến cố nào trực tiếp gây tắc động mạch vành?", ["Tăng áp lực đổ đầy thất trái.", "Hình thành huyết khối trên mảng xơ vữa bị tổn thương.", "Giảm khả năng giãn của cơ tim."], 1, "Tổn thương mảng xơ vữa có thể thúc đẩy hình thành huyết khối gây tắc.", "occlusion"],
    ["duration", "Hậu quả thiếu máu", "Thiếu máu cục bộ kéo dài có thể gây hậu quả nào tại vùng cơ tim do nhánh mạch bị tắc cấp máu?", ["Tăng tưới máu tại vùng cơ tim bị ảnh hưởng.", "Duy trì cung cấp oxy nhờ máu trong buồng thất.", "Tổn thương không hồi phục và hoại tử cơ tim."], 2, "Thiếu máu cục bộ kéo dài có thể dẫn đến hoại tử cơ tim. Mô phỏng không xác định thời gian xuất hiện hoặc phạm vi hoại tử.", "injury"],
    ["branch", "Phân tích mô hình", "Trong mô hình tắc nhánh liên thất trước (LAD), nhánh nào vẫn được biểu diễn có dòng máu?", ["Nhánh mũ (LCx).", "Đoạn LAD phía sau vị trí tắc.", "Cả LAD và LCx đều được biểu diễn mất dòng máu."], 0, "Kịch bản chỉ chặn LAD; nhánh mũ vẫn có hạt. Đây là lựa chọn minh họa, không mô tả mọi người bệnh.", "occlusion"],
    ["limits", "Giới hạn mô phỏng", "Có thể suy ra phạm vi nhồi máu cơ tim từ mật độ hạt trong mô phỏng này không?", ["Có, mật độ hạt phản ánh diện tích cơ tim hoại tử.", "Không, mô hình chưa tích hợp bản đồ vùng tưới máu cơ tim.", "Có, nếu đối chiếu số hạt giữa LAD và LCx."], 1, "Hạt chỉ minh họa dòng. Số hạt và thời gian phát không phải phép đo lâm sàng.", "injury"],
  ],
  stenosis: [
    ["wall", "Cơ chế bệnh sinh", "Mảng xơ vữa trong bệnh động mạch vành hình thành ở cấu trúc nào?", ["Thành động mạch vành.", "Nội mạc buồng thất trái.", "Màng ngoài tim."], 0, "Mảng xơ vữa tích tụ trong thành động mạch và có thể làm hẹp lòng mạch.", "plaque"],
    ["demand", "Tưới máu cơ tim", "Hẹp động mạch vành có thể ảnh hưởng thế nào đến khả năng đáp ứng nhu cầu oxy tăng của cơ tim?", ["Bảo đảm tăng cung cấp oxy tương ứng với mọi mức nhu cầu.", "Hạn chế khả năng tăng tưới máu cơ tim.", "Không ảnh hưởng vì cơ tim nhận oxy trực tiếp từ máu trong buồng thất."], 1, "Mạch vành bị hẹp có thể không cung cấp đủ máu giàu oxy cho nhu cầu cơ tim.", "limited-flow"],
    ["difference", "Phân biệt cơ chế bệnh sinh", "Đặc điểm nào phân biệt kịch bản hẹp động mạch vành này với kịch bản tắc hoàn toàn do huyết khối?", ["Mất dòng máu đồng thời ở tất cả các nhánh vành.", "Xuất hiện hoại tử cơ tim ngay khi có hẹp mạch.", "Vẫn còn dòng máu qua vị trí hẹp được đánh dấu."], 2, "Kịch bản giữ một phần hạt qua đoạn hẹp; không dùng cục huyết khối chặn hoàn toàn như bài nhồi máu.", "limited-flow"],
    ["density", "Giới hạn mô phỏng", "Giảm mật độ hạt phía sau vị trí hẹp biểu thị nội dung nào?", ["Minh họa định tính sự hạn chế tưới máu.", "Lưu lượng mạch vành đã được định lượng bằng mL/phút.", "Tỷ lệ hẹp lòng mạch đo trên hình ảnh của người bệnh."], 0, "Mật độ hạt là ký hiệu học tập. Mô hình không tính lưu lượng, vận tốc hay phần trăm hẹp.", "limited-flow"],
  ],
  spasm: [
    ["plaque", "Phân biệt cơ chế bệnh sinh", "Nhận định nào đúng về mối liên quan giữa co thắt động mạch vành và xơ vữa?", ["Co thắt chỉ xảy ra tại vị trí có mảng xơ vữa.", "Co thắt chỉ xuất hiện sau nhồi máu cơ tim.", "Co thắt có thể xảy ra ở động mạch vành không có mảng xơ vữa."], 2, "Co thắt thành động mạch vành có thể xảy ra ngay cả khi không có mảng xơ vữa.", "spasm"],
    ["purple", "Phân tích mô hình", "Vòng tím trong giai đoạn co thắt đánh dấu cấu trúc hoặc biến cố nào?", ["Huyết khối di chuyển trong động mạch vành.", "Vị trí co thắt giả định của nhánh LAD.", "Ranh giới vùng cơ tim đã hoại tử."], 1, "Vòng tím chỉ đánh dấu vị trí co thắt trong bài; không phải hình huyết khối hoặc bản đồ tổn thương.", "spasm"],
    ["return", "Diễn tiến mô phỏng", "Ở giai đoạn hết co thắt trong kịch bản, dòng máu được biểu diễn như thế nào?", ["Dòng máu được khôi phục qua vị trí co thắt.", "Dòng máu vẫn bị chặn hoàn toàn tại vị trí co thắt.", "Dòng máu đổi chiều từ đoạn xa về đoạn gần của LAD."], 0, "Bài mô phỏng chọn một pha hồi phục. Đây không phải dự đoán diễn tiến của mọi cơn co thắt.", "recovery"],
    ["safety", "Giới hạn mô phỏng", "Việc khôi phục dòng máu trong mô phỏng cho phép rút ra kết luận nào?", ["Mọi cơn co thắt đều không gây tổn thương cơ tim.", "Chỉ mô tả pha hồi phục được chọn, không xác định mức độ tổn thương của người bệnh.", "Có thể loại trừ thiếu máu cơ tim nếu dòng hạt trở lại."], 1, "Không suy diễn tiên lượng hoặc mức độ tổn thương cơ tim từ hoạt ảnh. Co thắt nặng có thể cản trở tưới máu cơ tim.", "recovery"],
  ],
};
const core: Record<keyof typeof coronaryScenarios, { question: string; labels: string[]; explanation: string }> = {
  infarction: { question: "Tắc nhánh liên thất trước (LAD) làm giảm tưới máu trực tiếp ở vùng nào?", labels: ["Toàn bộ cơ tim, không phụ thuộc phân bố động mạch vành.", "Vùng cơ tim do đoạn LAD phía sau vị trí tắc cấp máu.", "Máu trong buồng thất trái, không ảnh hưởng tưới máu cơ tim."], explanation: "Tắc LAD làm giảm dòng máu đến vùng cơ tim do nhánh này cấp máu ở phía sau chỗ tắc. Cần phân biệt tưới máu cơ tim với dòng máu qua các buồng tim." },
  stenosis: { question: "Nhận định nào phù hợp với kịch bản hẹp động mạch vành đang quan sát?", labels: ["Vẫn còn dòng máu qua đoạn hẹp; chưa thể kết luận có nhồi máu cơ tim.", "Sự hiện diện của mảng xơ vữa xác định tình trạng tắc hoàn toàn do huyết khối."], explanation: "Kịch bản minh họa hạn chế tưới máu qua đoạn hẹp. Hẹp động mạch vành không đồng nghĩa với tắc hoàn toàn hoặc hoại tử cơ tim." },
  spasm: { question: "Cơ chế trực tiếp gây cản trở dòng máu trong kịch bản co thắt động mạch vành là gì?", labels: ["Co thắt thành động mạch làm giảm khẩu kính lòng mạch.", "Huyết khối hình thành tại mảng xơ vữa bị tổn thương."], explanation: "Kịch bản mô tả cản trở dòng máu do co thắt thành mạch, không giả định có huyết khối. Hai cơ chế này cần được phân biệt." },
};
export const coronaryQuizDecks = Object.fromEntries(Object.entries(coronaryScenarios).map(([key, scenario]) => {
  const variant = key as keyof typeof coronaryScenarios;
  const questions: QuizQuestion[] = [{ ...scenario.quiz, question: core[variant].question, explanation: core[variant].explanation, options: scenario.quiz.options.map((option, i) => ({ ...option, label: core[variant].labels[i]! })), id: "core", kind: "Kiến thức nền tảng", stageId: variant === "infarction" ? "occlusion" : variant === "stenosis" ? "limited-flow" : "spasm" }, ...extras[variant].map(([id, kind, question, options, correct, explanation, stageId]) => ({ id, kind, question, options: options.map((label, index) => ({ id: String(index), label })), correctId: String(correct), explanation, stageId, sourceIds: [scenario.sources[0]!.id] }))];
  return [variant, questions];
})) as Record<keyof typeof coronaryScenarios, QuizQuestion[]>;
